elastic/search-ui

packages/react-search-ui-views/src/SearchBox.js
packages/react-search-ui-views/src/styles/themes/reference-ui/_base.scss
packages/react-search-ui-views/src/styles/themes/reference-ui/components/_search-box.scss
packages/react-search-ui-views/stories/SearchBox.stories.js

PR to add styling to the autocomplete and query suggestions.
Note:
- `highlightedIndex` and `selectedItem` were removed.
- I reduced the amount of results per section to 3 to reduce the effect of so many results being overwhelming.

Style Search UI autocomplete/suggestions 

---

ADVANCED.md

FYI, my editor / prettier automatically formats Markdown, so there's a bunch of formatting changes in here as well.

Updated publishing instructions

---

CONTRIBUTING.md
README.md

Additional details on signing the CLA.

add initial contributing.md

---

CHANGELOG.md
examples/sandbox/package.json
lerna.json
packages/react-search-ui/package-lock.json
packages/react-search-ui/package.json
packages/react-search-ui/src/containers/SearchBox.js
packages/react-search-ui/src/containers/__tests__/SearchBox.test.js

This PR merges hotfix changes for 0.6.1 back to master.

Merge v0.6

---

LICENSE

Really minor update to LICENSE (removed instructions and brackets)

minor change to license

---

examples/sandbox/src/App.js
packages/react-search-ui/src/containers/PagingInfo.js
packages/react-search-ui/src/containers/ResultsPerPage.js
packages/react-search-ui/src/containers/Sorting.js
packages/react-search-ui/src/containers/__tests__/PagingInfo.test.js
packages/react-search-ui/src/containers/__tests__/ResultsPerPage.test.js
packages/react-search-ui/src/containers/__tests__/Sorting.test.js
packages/react-search-ui/src/containers/__tests__/__snapshots__/PagingInfo.test.js.snap
packages/react-search-ui/src/containers/__tests__/__snapshots__/ResultsPerPage.test.js.snap
packages/react-search-ui/src/containers/__tests__/__snapshots__/Sorting.test.js.snap

Containers no longer hide themselves by default before first search

---

packages/react-search-ui-views/src/styles/themes/reference-ui/components/_multi-checkbox-facet.scss

Added cursor pointer to facet checkbox
Added cursor pointer to facet checkbox
Fixes #217

Added cursor pointer to facet checkbox

---

examples/sandbox/src/App.js

Fixed strange loading behavior in Sandbox App
Before:
After:
Used `wasSearched` to conditionally load `ResultsPerPage` component
N/A

Fix sandbox loading jank

---

README.md

Updated some words. Let me know what you think.

Updated primary README

---

ADVANCED.md
README.md

Reworked the "Headless Core" section of the Advanced Guide

Reworked the "Headless Core" section of the ADVANCED guide

---

ADVANCED.md
README.md

Added a live demo link to the README. The live demo is deployed from the `stable` branch to Netlify.
- Added the link to the README.
- Added instructions in Contributor guide to update the `stable` branch when pushing a new release.

Added a live demo

---

README.md

Added the Site Search demo link

Added the Site Search demo link

---

examples/sandbox/src/App.js

Removed weights from the Sandbox, so that weights could be configured via the App Search dashboard.
Also removed the debounce on autocomplete, for faster autocompletion.

Removed weights from sandbox

---

packages/package-lock.json
packages/react-search-ui-views/package-lock.json
packages/react-search-ui-views/package.json
packages/react-search-ui/package-lock.json
packages/react-search-ui/package.json
packages/search-ui-app-search-connector/package-lock.json
packages/search-ui-app-search-connector/package.json
packages/search-ui-site-search-connector/package-lock.json
packages/search-ui-site-search-connector/package.json
packages/search-ui/package-lock.json
packages/search-ui/package.json

Error:
```
Module not found: Can't resolve 'core-js/modules/es6.array.copy-within'
in '/Users/kellen/Repos/swiftype/video-game-search/node_modules/@elastic
/react-search-ui-views/es'
```
I fixed this by setting an explicit dependency on core-js in our
package.json. It works in certain cases without it somehow. I'm not
100% sure about what was going on here, but this should solve the issue.
- Added a dependency on `core-js@2` to all packages
Fixes #262

Fixed core-js error

---

ADVANCED.md
CONTRIBUTING.md

Moved CONTRIBUTING.md and added canary builds
- Moved contributing section out of the ADVANCED guide and into CONTRIBUTING.md
- Added a section on canary publishes at the bottom.

Moved CONTRIBUTING.md and added canary builds

---

CONTRIBUTING.md
README.md

Gliiiiiiiiitch
- Gliiiiiiiiitch
Fixes #Gliiiiiiiiitch

Gliiiiiiiiitch

---

README.md

I wanted this to emphasize Elastic App Search, but not scare off people who aren't interested in App Search.

Reworded README.md description

---

README.md
packages/react-search-ui-views/package.json
packages/react-search-ui/package.json
packages/search-ui-app-search-connector/package.json
packages/search-ui-site-search-connector/package.json
packages/search-ui/package.json

Readme link fixes and updates for NPM and attribution.
- Updated directory in individual package.json files 
- Added UTM tags to links leading to App / Site Search

Readme updates

---

ADVANCED.md

I noticed a few broken links in the ADVANCED docs while working on my onboarding project, and thought I'd open up a quick PR to fix them here.
Note: If you'd rather keep these as relative links instead of absolute, and only fix the pathing instead, I can do this - just let me know!
- Fix a few broken relative links in ADVANCED.md

Fix broken relative links in ADVANCED.md

---

README.md

Small PR to remove beta references from README

Remove beta reference from README

---

packages/react-search-ui-views/src/Paging.js
packages/react-search-ui-views/src/__tests__/__snapshots__/Paging.test.js.snap

We were considering replacing the pagination library in this issue https://github.com/elastic/search-ui/issues/308, but since we're not sure when we will do this, I wanted to apply a quick fix for the current pagination library.
Added English locale to rc-pagination view.
Fixes https://github.com/elastic/search-ui/issues/407

Fix pagination locale

---

examples/sandbox/src/App.js

Changed sandbox to load search results on load

Changed sandbox to load search results on load

---

examples/elasticsearch/package-lock.json
examples/sandbox/package-lock.json

I noticed that many PRs have these files updated.
I think people do that because running npm install on fresh Search UI
repo updates these files and repo becomes dirty.
This PR simply contains changes that happen to package-lock files
after running npm install.

Update package-lock files

---

ADVANCED.md
CONTRIBUTING.md
packages/search-ui/src/SearchDriver.js
packages/search-ui/src/__tests__/actions/a11yNotify.test.js
packages/search-ui/src/actions/a11yNotify.js
packages/search-ui/src/actions/addFilter.js
packages/search-ui/src/actions/clearFilters.js
packages/search-ui/src/actions/removeFilter.js
packages/search-ui/src/actions/reset.js
packages/search-ui/src/actions/setCurrent.js
packages/search-ui/src/actions/setFilter.js
packages/search-ui/src/actions/setResultsPerPage.js
packages/search-ui/src/actions/setSearchTerm.js
packages/search-ui/src/actions/setSort.js
packages/search-ui/src/actions/trackAutocompleteClickThrough.js
packages/search-ui/src/actions/trackClickThrough.js

Documented and enhanced the debug flag
- Documented the debug flag in the CONTRIBUTING guide
- Added a console warning if the debug flag is enabled to help
developers remember not to enable this flag in production
- Exported actions globally when debug is true

Documented and enhanced the debug flag

---

packages/search-ui-app-search-connector/README.md
packages/search-ui-app-search-connector/src/AppSearchAPIConnector.js

Updated the App Search API Connector to accept additional options, which will be passed through to the API client.
Closes https://github.com/elastic/search-ui/issues/468

Added AppSearchAPIConnector additional options

---

packages/react-search-ui-views/package.json
packages/react-search-ui-views/src/Result.js
packages/react-search-ui-views/src/__tests__/Result.test.js
packages/react-search-ui-views/src/__tests__/__snapshots__/Result.test.js.snap
packages/react-search-ui-views/src/__tests__/view-helpers/getUrlSanitizer.test.js
packages/react-search-ui-views/src/view-helpers/getUrlSanitizer.js
packages/react-search-ui-views/src/view-helpers/index.js

Added additional checks to the Result view component.

Additional checks on Result component

---

packages/react-search-ui-views/package.json
packages/react-search-ui-views/src/Result.js
packages/react-search-ui-views/src/__tests__/Result.test.js
packages/react-search-ui-views/src/__tests__/__snapshots__/Result.test.js.snap
packages/react-search-ui-views/src/__tests__/view-helpers/getUrlSanitizer.test.js
packages/react-search-ui-views/src/view-helpers/getUrlSanitizer.js
packages/react-search-ui-views/src/view-helpers/index.js

Cherry-picks https://github.com/elastic/search-ui/pull/481 forward from branch 1.3.

Additional checks on Result component (#481)

---

examples/sandbox/package-lock.json
packages/react-search-ui-views/package.json
packages/react-search-ui/package.json
packages/search-ui-app-search-connector/package.json
packages/search-ui-site-search-connector/package.json
packages/search-ui/package.json

Move @babel/runtime and autoprefixer to devDependencies

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
README.md

Added issue templates and updated the discuss forum link in the description.

Update issue templates

---

examples/sandbox/README.md

Quick cleanup of the Sandbox README

Fix Sandbox README

---

packages/search-ui-workplace-search-connector/src/WorkplaceSearchAPIConnector.ts
packages/search-ui-workplace-search-connector/src/__tests__/WorkplaceSearchAPIConnector.test.ts

Add tests to the Workplace Search connector

---

packages/search-ui-app-search-connector/src/AppSearchAPIConnector.ts
packages/search-ui-app-search-connector/src/__tests__/AppSearchAPIConnector.test.ts

Fix hostIdentifier is required even when not using SwiftType

---

docs/search-ui/connectors-elasticsearch.mdx
packages/search-ui-elasticsearch-connector/README.md

- Includes how to run the connector within a node.js server.

Elasticsearch Connector Documentation 

---

.github/workflows/doc-prod.yml

Adds deployment for prod docs.
Adds a new action to build to vercel prod
Action runs on pushes to master (aka on merge)
https://github.com/elastic/search-ui/pull/670
https://github.com/elastic/search-ui/pull/691

adds action to deploy to prod

---

.vscode/launch.json
examples/sandbox/src/pages/workplace-search/index.css
examples/sandbox/src/pages/workplace-search/index.js
packages/search-ui-workplace-search-connector/README.md
packages/search-ui-workplace-search-connector/src/WorkplaceSearchAPIConnector.ts
packages/search-ui-workplace-search-connector/src/__tests__/WorkplaceSearchAPIConnector.test.ts
packages/search-ui/src/SearchDriver.ts
packages/search-ui/src/__tests__/SearchDriver.test.ts
packages/search-ui/src/__tests__/actions/trackAutocompleteClickThrough.test.ts
packages/search-ui/src/__tests__/actions/trackClickThrough.test.ts
packages/search-ui/src/actions/trackAutocompleteClickThrough.ts
packages/search-ui/src/actions/trackClickThrough.ts
packages/search-ui/src/test/helpers.ts
packages/search-ui/src/types/index.ts

This is a PR that cherry-picked all the commits from the [next](https://github.com/elastic/search-ui/commits/next) branch that were not present in the [master](https://github.com/elastic/search-ui/commits/master) branch and fixed the conflicts. In the last commit I add a couple fixes for TS errors and tests.
Once this PR is merged, I'll delete the `next` branch.

Add all commits from next branch into master branch

---

examples/sandbox/package.json
packages/search-ui-elasticsearch-connector/package.json
packages/search-ui-elasticsearch-connector/src/handlers/autocomplete/__tests__/results.test.ts
packages/search-ui-elasticsearch-connector/src/handlers/common.ts
packages/search-ui-elasticsearch-connector/src/handlers/search/Configuration.ts
packages/search-ui-elasticsearch-connector/src/handlers/search/__tests__/Configuration.test.ts
packages/search-ui-elasticsearch-connector/src/handlers/search/__tests__/Response.test.ts
packages/search-ui-elasticsearch-connector/src/handlers/search/__tests__/index.test.ts
packages/search-ui-elasticsearch-connector/src/handlers/search/index.ts
packages/search-ui-elasticsearch-connector/src/index.ts
yarn.lock

fixes https://github.com/elastic/search-ui/issues/714

714 fix bug with elasticsearch connector and click analytics

---

README.md
docs/overview.mdx

Building docs

---

.github/workflows/build_docs.yml
docs/api-actions.mdx
docs/api-configuration.mdx
docs/api-react-components-error-boundary.mdx
docs/api-react-components-facet.mdx
docs/api-react-components-paging-info.mdx
docs/api-react-components-paging.mdx
docs/api-react-components-result.mdx
docs/api-react-components-results-per-page.mdx
docs/api-react-components-results.mdx
docs/api-react-components-search-box.mdx
docs/api-react-components-sorting.mdx
docs/api-react-core.mdx
docs/api-react-hocs.mdx
docs/api-state.mdx
docs/connectors-api-app-search.mdx
docs/connectors-api-custom-connector.mdx
docs/connectors-api-elasticsearch.mdx
docs/connectors-api-site-search.mdx
docs/connectors-api-workplace-search.mdx
docs/guides-creating-your-own-components.mdx
docs/guides-customizing-styles-and-html.mdx
docs/guides-debugging.mdx
docs/guides-extending-view-components.mdx
docs/guides-philosphy.mdx
docs/overview.mdx
docs/tutorials-app-search.mdx
docs/tutorials-elasticsearch.mdx
docs/tutorials-workplace-search.mdx

Third and final end-to-end test

Doc build end-to-end 3

---

docs/tutorials-elasticsearch.mdx

Update the CORS setting to wildcard the `allow-headers` setting.

[docs] Update CORS instructions for allow-headers

---

.github/workflows/builder-docs-elastic-co.yml
docs/api-event-hooks.mdx

Updates to the production Action.
Also fixes a slash -- missed this on initial pass. :)

Update builder & add missing slash

---

examples/sandbox/src/pages/customizing-styles-and-html/custom.css
examples/sandbox/src/pages/customizing-styles-and-html/index.js

Fixing custom styles being applied to all examples instead of just custom styles example

Isolate custom styles to custom styles example

---

examples/sandbox/package.json
examples/sandbox/src/Router.js
examples/sandbox/src/index.js
yarn.lock

This PR adds basic APM RUM config to our sandbox application. This will allow us to start collecting metrics from our codesandbox examples and find opportunities for better integration of Search UI and APM RUM.

Add APM RUM to sandbox

---

examples/sandbox/package.json

Closes https://github.com/elastic/enterprise-search-team/issues/1604
Just adding some metadata that can be recognized by codesandbox: https://codesandbox.io/docs/importing#import-from-github

Improve discoverability of sandbox on codesandbox

---

docs/tutorials-elasticsearch.mdx

code example in tutorials-elasticsearch does not work

---

.gitignore
docs/api-connectors-elasticsearch.mdx
examples/sandbox/src/pages/elasticsearch/index.js
packages/search-ui-elasticsearch-connector/package.json
packages/search-ui-elasticsearch-connector/src/handlers/search/Configuration.ts
packages/search-ui-elasticsearch-connector/src/handlers/search/Request.ts
packages/search-ui-elasticsearch-connector/src/handlers/search/__tests__/Configuration.test.ts
packages/search-ui-elasticsearch-connector/src/handlers/search/__tests__/Request.test.ts

777 fix filters

---

examples/sandbox/src/pages/ecommerce/CategoryTvs.js
examples/sandbox/src/pages/ecommerce/CustomResultView.js
examples/sandbox/src/pages/ecommerce/Search.js
examples/sandbox/src/pages/ecommerce/config.js

This PR improves the Ecommerce category page to include category-specific facets:

Ecommerce category page

---

docs/solutions-ecommerce-product-listing-page.mdx
examples/sandbox/src/pages/ecommerce/Category.js

Recreated PR https://github.com/elastic/search-ui/pull/818
and resolved merge conflicts

Category page docs 2 

---

packages/react-search-ui-views/src/SearchBox.tsx
packages/react-search-ui-views/src/__tests__/SearchBox.test.tsx
packages/react-search-ui-views/src/__tests__/__snapshots__/SearchBox.test.tsx.snap

fixes https://github.com/elastic/search-ui/issues/830

Fixes searchbox autocompleteSuggestion type

---

docs/solutions-ecommerce-product-listing-page.mdx
examples/sandbox/src/pages/ecommerce/CustomResultView.js
examples/sandbox/src/pages/ecommerce/config.js

This PR adds variants section to product listing page docs and adds variants support to our demo:

Category page 3

---

packages/search-ui/README.md

Links on search-ui were broken
- Fixing links to search-ui docs

Update broken links in search-ui package README

---

packages/search-ui-app-search-connector/src/AppSearchAPIConnector.ts
packages/search-ui-app-search-connector/src/__tests__/AppSearchAPIConnector.test.ts

Fix cacheResponses boolean type error 

---

docs/api-plugins-analytics-plugin.mdx
docs/nav-searchui.docnav.json
packages/search-ui-analytics-plugin/README.md

Adds search-ui behavioral analytics plugin documentation

Analytics Plugin Documentation

---

.ci/jobs/search-ui.yml
.ci/jobs/searchui.yml
CONTRIBUTING.md
INTERNAL.md
README.md
docs/api-connectors-elasticsearch.mdx
docs/api-connectors-workplace-search.mdx
docs/guides-adding-search-bar-to-header.mdx
docs/guides-customizing-styles-and-html.mdx
docs/guides-search-as-you-type.mdx
docs/guides-using-with-vue-js.mdx
docs/overview.mdx
docs/solutions-ecommerce-autocomplete.mdx
docs/solutions-ecommerce-carousel.mdx
docs/solutions-ecommerce-category-page.mdx
docs/solutions-ecommerce-search-page.mdx
docs/solutions-ecommerce.mdx
docs/tutorials-elasticsearch.mdx
examples/sandbox/README.md
packages/search-ui-elasticsearch-connector/README.md
packages/search-ui-workplace-search-connector/README.md
packages/search-ui/src/types/index.ts

This PR replaces all references to `master` with `main`

Replace references to master with main

---

docs/overview.mdx
packages/search-ui-engines-connector/package.json

- Add publish config for engines connector. Required for when publishing a scoped public package for the first time.

Overview update + add publish config for engines Connector

---

examples/sandbox/src/pages/elasticsearch-with-analytics/index.js

Add required param for createTracker function

Fix error in sandbox example

---

docs/nav-searchui.docnav.json

Update search ui doc API reference connectors API nav link

update nav app search connectors doc

---

packages/react-search-ui-views/src/styles/themes/reference-ui/components/_paging.scss

Updating styling to match the old styles. Top one is with changes, bottom is older version of search ui.

Pagination style fix

---

docs/nav-searchui.docnav.json

Updates `nav-searchui.docnav.json` to work with new syntax

Update nav-searchui.docnav.json for new syntax

---

packages/search-ui/src/__tests__/actions/setFilter.test.ts
packages/search-ui/src/actions/setFilter.ts

Set array value properly in filters

---

docs/overview.mdx

Triggers a doc build.
Deletes test element.
N/A

Trigger a doc build

---

docs/reference/api-react-search-provider.md
docs/reference/api-react-with-search.md
docs/reference/api-reference.md
docs/reference/basic-usage.md
docs/reference/tutorials-app-search.md

Fix external links that incorrectly use `.md` instead of `.html`.
cc @leemthompo  (I can't add reviewers!!)

[docs] Fix external links
