- packages/react-search-ui-views/src/types/ValueFilterValue.js
- packages/react-search-ui/src/types/ValueFilterValue.js
- packages/search-ui/src/URLManager.js
- packages/search-ui/src/__tests__/URLManager.test.js
- packages/search-ui/src/__tests__/preserveTypesEncoder.test.js
- packages/search-ui/src/__tests__/queryString.test.js
- packages/search-ui/src/preserveTypesEncoder.js
- packages/search-ui/src/queryString.js
Fixes #42 #44 
The URL scheme I had for filters was insufficient. It needs to be able to handle the following scenarios:
```
{
“all”: [{
// Range with type Number
{"visitors": {
"from": 1,
"to": 100
}},
// Range with type Date
{"date_established": {
"from": "1900-01-01T12:00:00+00:00",
"to": "1950-01-01T00:00:00+00:00"
}},
// Geo with type Geolocation
{"location": {
"center": "37.386483, -122.083842",
"distance": 300,
"unit": "km"
}},
// Value with type Text
{"world_heritage_site": "true"},
// Value with type Date
{“created_date”: "1900-01-01T12:00:00+00:00"},
// Value with Type Number
{“visitors”: 100},
// Combining with "all"
{“category”: ”fun”},
{“category”: ”healthy”}
// Nested "or"s
{“category”: [”gradeA”, “gradeB”]} 
}],
// Combining with "any"
“or”: { … },
// Combining with "none" …
```
> Reworked how query filters are maintained in the URL

- examples/sandbox/src/App.js
- packages/search-ui-app-search-connector/src/responseAdapter.js
- packages/search-ui/src/SearchDriver.js
- packages/search-ui/src/__tests__/SearchDriver.test.js
This keeps query related configuration in one place. In the future
we'll be adding to adjust autocompleteQuery and suggestQuery as
well.
There's a lot of whitespace in this PR, I mainly just nested some configuration options under a "searchQuery" property.
>  Consolidated search config into "searchQuery"

- examples/sandbox/src/App.js
- packages/react-search-ui/src/containers/SearchBox.js
- packages/react-search-ui/src/containers/__tests__/SearchBox.test.js
- packages/search-ui-app-search-connector/src/AppSearchAPIConnector.js
- packages/search-ui-app-search-connector/src/__tests__/AppSearchAPIConnector.test.js
- packages/search-ui/src/SearchDriver.js
- packages/search-ui/src/__tests__/actions/setSearchTerm.test.js
- packages/search-ui/src/actions/setSearchTerm.js
- packages/search-ui/src/test/helpers.js
https://github.com/elastic/search-ui/issues/105
- Added an option to `SearchBox` called `autocompleteResults`.
- Added a flag to `setSearchTerm` called `autocompleteResults`.
- Added a new connector method called `autocompleteResults`.
- Added a new state property called `autocompletedResults` (Note the "d").
When the `autocompelteResults` flag is true, a new API request will be invoked to fetch results for and populate `autocompletedResults`.
So basically, if you fire up the sandbox application and start typing, since the `autocompleteResults` flag is set to `true`, you will see API requests being fired off, and the results will actually be populated in state.
This makes them available for us to build a view to consume them, which will be added in a future PR.
> Added autocomplete results to state

- packages/react-search-ui-views/package-lock.json
- packages/react-search-ui-views/package.json
- packages/react-search-ui-views/src/SearchBox.js
- packages/react-search-ui-views/src/__tests__/__snapshots__/SearchBox.test.js.snap
- packages/react-search-ui-views/stories/SearchBox.stories.js
- packages/react-search-ui/src/containers/SearchBox.js
- packages/react-search-ui/src/containers/__tests__/SearchBox.test.js
Downshift was added to enable autocomplete. I've added 3 new parameters
to the SearchBox view:
- autocomplete - Whether or not to show autocompletes
- autocompleteItems - Accepts array of "Sections", so that we can
have titles above various types of autocomplete, i.e, suggestions and
results
- onSelectAutocomplete - A callback to trigger when a selection
is made in the autocomplete.
I'd like to merge this PR, then work on styling and building out the business logic concurrently in additional PRs.
> SearchBox to Downshift + autocomplete

- packages/react-search-ui-views/src/SearchBox.js
- packages/react-search-ui-views/src/types/Suggestion.js
- packages/react-search-ui-views/src/types/index.js
- packages/react-search-ui-views/stories/SearchBox.stories.js
There's a high likelihood that a user would want to separate the
two in the view. By combining the two before passing it to the view
I think we were doing too much.
> Seperated Results and Suggestions in SearchBox view

- examples/sandbox/src/App.js
- packages/react-search-ui-views/src/SearchBox.js
- packages/react-search-ui-views/src/__tests__/SearchBox.test.js
- packages/react-search-ui-views/src/__tests__/__snapshots__/SearchBox.test.js.snap
- packages/react-search-ui-views/src/styles/themes/reference-ui/components/_search-box.scss
- packages/react-search-ui-views/src/types/FieldValue.js
- packages/react-search-ui-views/stories/SearchBox.stories.js
- packages/react-search-ui/src/containers/SearchBox.js
- packages/react-search-ui/src/containers/__tests__/SearchBox.test.js
- packages/react-search-ui/src/containers/__tests__/__snapshots__/SearchBox.test.js.snap
- packages/react-search-ui/src/types/FieldValue.js
This PR completes the remaining work for to have a basic working Autocomplete with Search Results.
Design is documented here: https://github.com/elastic/search-ui/issues/113
Remaining work is captured here: https://github.com/elastic/search-ui/pull/140
- Added working example to the Sandbox
- Closes the autocomplete Autocomplete any time a query is submitted
- Ensure the autocomplete value is not changed whenever a result is selected
- Support for boolean configuration of autocompleteResults (explained in design doc)
- Updated `FieldValue` type to expect Arrays of values from the server.
To test this, run the sandbox app and play around with the autocomplete: https://github.com/elastic/search-ui/tree/master/examples/sandbox
To just play around with the view, you can run storybook:
```
cd …
```
> Full Autocomplete support for Search Results

- examples/sandbox/src/App.js
- packages/search-ui/src/SearchDriver.js
- packages/search-ui/src/__tests__/SearchDriver.test.js
This PR adds support for configuring autocomplete queries.
Design is documented here: https://github.com/elastic/search-ui/issues/113
To test this, run the sandbox app and play around with the autocomplete: https://github.com/elastic/search-ui/tree/master/examples/sandbox
You should see our "result_fields" config has now provided snippets for the autocomplete.
> Added configuration for autocomplete queries

- packages/react-search-ui-views/src/Autocomplete.js
- packages/react-search-ui-views/src/SearchBox.js
- packages/react-search-ui-views/stories/SearchBox.stories.js
- packages/react-search-ui/src/containers/SearchBox.js
This PR adds an additional prop to the `SearchBox` component which lets you customize the view of
just the Autocomplete dropdown, without having to customize the entire view of SearchBox.
The prop is `autocompleteView`
ex:
```jsx
<SearchBox
autocompleteResults={true}
autocompleteView
autocompleteView={props => (
<div className="sui-search-box__autocomplete-container">
Custom View
</div>
)}
/>
```
To test this you can run storybook:
```
cd packages/react-search-ui-views && npm run storybook
```
> Configurable autocomplete view

- examples/sandbox/src/App.js
- packages/react-search-ui-views/src/Autocomplete.js
- packages/react-search-ui-views/src/SearchBox.js
- packages/react-search-ui-views/src/__tests__/Autocomplete.test.js
- packages/react-search-ui-views/src/__tests__/SearchBox.test.js
- packages/react-search-ui-views/src/__tests__/__snapshots__/Autocomplete.test.js.snap
- packages/react-search-ui-views/src/__tests__/__snapshots__/SearchBox.test.js.snap
- packages/react-search-ui-views/src/index.js
- packages/react-search-ui/src/containers/Result.js
- packages/react-search-ui/src/containers/Results.js
- packages/react-search-ui/src/containers/SearchBox.js
- packages/react-search-ui/src/containers/__tests__/Result.test.js
- packages/react-search-ui/src/containers/__tests__/Results.test.js
- packages/react-search-ui/src/containers/__tests__/SearchBox.test.js
- packages/react-search-ui/src/containers/__tests__/__snapshots__/Result.test.js.snap
- packages/react-search-ui/src/containers/__tests__/__snapshots__/Results.test.js.snap
- packages/react-search-ui/src/containers/__tests__/__snapshots__/SearchBox.test.js.snap
- packages/react-search-ui/src/containers/index.js
- packages/search-ui-app-search-connector/src/AppSearchAPIConnector.js
- packages/search-ui-app-search-connector/src/__tests__/AppSearchAPIConnector.test.js
- packages/search-ui/src/__tests__/SearchDriver.test.js
- packages/search-ui/src/__tests__/actions/trackAutocompleteClickThrough.test.js
- packages/search-ui/src/__tests__/actions/trackClickThrough.test.js
- packages/search-ui/src/actions/index.js
- packages/search-ui/src/actions/trackAutocompleteClickThrough.js
- packages/search-ui/src/test/helpers.js
This PR adds support for configuring clickthrough tracking behavior on Autocomplete.
Design is documented here: https://github.com/elastic/search-ui/issues/113
Changes:
There are now two additional parameters you can pass to the `autocompleteResults` configuration: `shouldTrackClickThrough` and `clickThroughTags`.
```
<SearchBox
autocompleteResults={{
shouldTrackClickThrough: true,
clickThroughTags={['someTag']}
}}
```
- By default, a clickthrough event WILL be logged any time a user selects a "Result" item from an autocomplete. Note that this will NOT be logged when a "suggestion" is selected, which is not considered a clickthrough event.
- `shouldTrackClickThrough` is optional but can be set to be false to prevent that from occurring by default.
- `clickThroughTags` is optional, it …
> Added click tracking to autocompelte

- examples/sandbox/src/App.js
- packages/react-search-ui/src/containers/SearchBox.js
- packages/react-search-ui/src/containers/__tests__/SearchBox.test.js
- packages/search-ui/src/__tests__/actions/setSearchTerm.test.js
- packages/search-ui/src/actions/setSearchTerm.js
- packages/search-ui/src/test/helpers.js
This PR adds support for `autocompleteMinimumCharacters` on Autocomplete.
Design is documented here: https://github.com/elastic/search-ui/issues/113
```
<SearchBox
autocompleteMinimumCharacters={3}
autocompleteResults={{
titleField: "title",
urlField: "nps_link"
}}
/>
```
This prevent the autocomplete box from making a query or showing until at least the minimum amount of characters have been entered.
> Added autocompleteMinimumCharacters to SearchBox

- examples/sandbox/package.json
- lerna.json
- packages/react-search-ui-views/CHANGELOG.md
- packages/react-search-ui-views/package.json
- packages/react-search-ui/package.json
- packages/react-search-ui/src/SearchProvider.js
- packages/search-ui-app-search-connector/package.json
- packages/search-ui-elasticsearch-connector/package.json
- packages/search-ui-site-search-connector/package.json
- packages/search-ui/package.json
Moved SearchDriver initialization to ComponentDidMount in SearchProvider
to make sure that Server Side Rendering does not attempt to render
Search UI. Search UI is dependent on a browser environment to support
history and routing. Until we can find a better way to support
SSR, I have moved it to CDM to at least avoid errors.
> Moved SearchDriver init to CDM in SearchProvider

- packages/search-ui-site-search-connector/src/SiteSearchAPIConnector.js
- packages/search-ui-site-search-connector/src/__tests__/SiteSearchAPIConnector.test.js
- packages/search-ui-site-search-connector/src/__tests__/__snapshots__/SiteSearchAPIConnector.test.js.snap
- packages/search-ui-site-search-connector/src/responseAdapters.js
This PR adds autocomplete support to the Site Search connector.
Design is documented here: https://github.com/elastic/search-ui/issues/113.
To test this, run the sandbox app and play around with the autocomplete: https://github.com/elastic/search-ui/tree/master/examples/sandbox.
You'll need to switch to use the Site Search connector. You can use the following credentials in `App.js`.
```js
import SiteSearchAPIConnector from "@elastic/search-ui-site-search-connector";
```
```js
const connector = new SiteSearchAPIConnector({
engineKey: "Z43R5U3HiDsDgpKawZkA",
documentType: "national-parks",
additionalOptions: () => ({})
});
```
> Added autocomplete support for Site Search

- examples/sandbox/src/App.js
- packages/search-ui-app-search-connector/src/AppSearchAPIConnector.js
- packages/search-ui-app-search-connector/src/__tests__/AppSearchAPIConnector.test.js
- packages/search-ui-site-search-connector/src/__tests__/SiteSearchAPIConnector.test.js
- packages/search-ui-site-search-connector/src/requestAdapter.js
This change allows [Request State](https://github.com/elastic/search-ui/tree/master/packages/react-search-ui#state) parameters to be provided in query configuration. 
Design is documented here: https://github.com/elastic/search-ui/issues/113.
Request State is things like "filters", "resultsPerPage", "sort", etc. Parameters that get fed into a search query but are managed as part of state. I.e., if a user selects a "sort" from a page, it gets passed to the query.
ex.
```jsx
<SearchProvider
config={{
autocompleteQuery: {
results: {
search_fields: {
title: {},
description: {}
},
result_fields: {
title: {
snippet: {
size: 100,
fallback: true
}
}
},
current: 2,
resultsPerPage: 5,
filters: [
{
field: "world_heritage_site",
values: ["true"],
type: "all"
}
],
sortDirection: "desc",
sortField: …
```
> Allow query configuration of  sort, filters, etc. for Autocomplete queries

- packages/react-search-ui/src/containers/ErrorBoundary.js
- packages/react-search-ui/src/containers/Paging.js
- packages/react-search-ui/src/containers/PagingInfo.js
- packages/react-search-ui/src/containers/Result.js
- packages/react-search-ui/src/containers/Results.js
- packages/react-search-ui/src/containers/ResultsPerPage.js
- packages/react-search-ui/src/containers/SearchBox.js
- packages/react-search-ui/src/containers/Sorting.js
- packages/react-search-ui/src/containers/__tests__/ErrorBoundary.test.js
- packages/react-search-ui/src/containers/__tests__/Paging.test.js
- packages/react-search-ui/src/containers/__tests__/PagingInfo.test.js
- packages/react-search-ui/src/containers/__tests__/Result.test.js
- packages/react-search-ui/src/containers/__tests__/Results.test.js
- packages/react-search-ui/src/containers/__tests__/ResultsPerPage.test.js
- packages/react-search-ui/src/containers/__tests__/SearchBox.test.js
- packages/react-search-ui/src/containers/__tests__/Sorting.test.js
- packages/react-search-ui/src/containers/__tests__/__snapshots__/ErrorBoundary.test.js.snap
- packages/react-search-ui/src/containers/__tests__/__snapshots__/Paging.test.js.snap
- packages/react-search-ui/src/containers/__tests__/__snapshots__/PagingInfo.test.js.snap
- packages/react-search-ui/src/containers/__tests__/__snapshots__/Result.test.js.snap
- packages/react-search-ui/src/containers/__tests__/__snapshots__/Results.test.js.snap
- packages/react-search-ui/src/containers/__tests__/__snapshots__/ResultsPerPage.test.js.snap
- packages/react-search-ui/src/containers/__tests__/__snapshots__/SearchBox.test.js.snap
- packages/react-search-ui/src/containers/__tests__/__snapshots__/Sorting.test.js.snap
View rendering logic was mounting views in such a way that
on every state change, the entire view was being unmounted and
remounted. This was very inefficient and caused issues with passing
custom props into views.
This was also causing issues on https://swiftype.com/ search. 
Particularly on mobile devices.
Fixes #160 
This fix was actually fairly simple, view just needed to be rendered
like this:
```js
View({
current,
resultsPerPage,
totalPages,
onChange: setCurrent
});
```
Instead of:
```jsx
<View
current={current}
resultsPerPage={resultsPerPage}
totalPages={totalPages}
onChange={setCurrent}
/>
```
Most of the files changed in this PR are just adjusting
specs to work with this new approach.
To test this, run the sandbox app and play around with the autocomplete: …
> Fix view rendering logic

- examples/sandbox/src/App.js
- packages/react-search-ui-views/src/Autocomplete.js
- packages/react-search-ui-views/src/SearchBox.js
- packages/react-search-ui-views/src/__tests__/Autocomplete.test.js
- packages/react-search-ui-views/src/__tests__/SearchBox.test.js
- packages/react-search-ui-views/src/__tests__/__snapshots__/Autocomplete.test.js.snap
- packages/react-search-ui/src/containers/SearchBox.js
- packages/react-search-ui/src/containers/__tests__/SearchBox.test.js
- packages/react-search-ui/src/types/Suggestion.js
- packages/react-search-ui/src/types/index.js
- packages/search-ui-app-search-connector/src/AppSearchAPIConnector.js
- packages/search-ui-app-search-connector/src/__tests__/AppSearchAPIConnector.test.js
- packages/search-ui-site-search-connector/src/SiteSearchAPIConnector.js
- packages/search-ui-site-search-connector/src/__tests__/SiteSearchAPIConnector.test.js
- packages/search-ui-site-search-connector/src/__tests__/__snapshots__/SiteSearchAPIConnector.test.js.snap
- packages/search-ui/src/SearchDriver.js
- packages/search-ui/src/__tests__/SearchDriver.test.js
- packages/search-ui/src/__tests__/actions/setSearchTerm.test.js
- packages/search-ui/src/actions/setSearchTerm.js
- packages/search-ui/src/test/helpers.js
This PR adds support for Query Suggestions to the autocomplete dropdown.
This issue documents the full design for this feature: https://github.com/elastic/search-ui/issues/113
Changes:
- Refactored the "autocompleteResults" method in the API Connectors to be a single method, called "autocomplete". This is better, because it's better to emit a single event and have the connector decide how many API calls they will need, rather than evoking two independent events, which an API might possibly be able to combine.
- BugFix: Autocomplete minimum chars ... renders on 3 characters, but doesn't perform new search until 4 characters
Testing:
To test this, run the sandbox app: https://github.com/elastic/search-ui/tree/master/examples/sandbox.
In `App.js`, play around with the `SearchBox` …
> Autocomplete suggestions support

- examples/sandbox/package.json
- examples/sandbox/src/App.js
- lerna.json
- packages/react-search-ui-views/package.json
- packages/react-search-ui/CHANGELOG.md
- packages/react-search-ui/package.json
- packages/search-ui-app-search-connector/package.json
- packages/search-ui-elasticsearch-connector/package.json
- packages/search-ui-site-search-connector/package.json
- packages/search-ui/CHANGELOG.md
- packages/search-ui/package.json
- packages/search-ui/src/SearchDriver.js
- packages/search-ui/src/__tests__/SearchDriver.test.js
This is a patch release for v0.5.x.
v0.5.2 included an unintentional breaking change. I reverted this change as it was meant for v0.6.x, not v0.5.x: https://github.com/elastic/search-ui/pull/164/commits/a65b0567340baac0593749098e0dab4aaf5c06fa.
I also fixed the dependencies in `@elastic/react-search-ui` to use fixed dependencies on other search-ui packages of the same version. That way, if you install `@elastic/react-search-ui@0.5.1`, you won't get `@elastic/search-ui@0.5.2`, which is not compatible.
> Release v0.5.3

- packages/search-ui-app-search-connector/src/AppSearchAPIConnector.js
- packages/search-ui-app-search-connector/src/__tests__/AppSearchAPIConnector.test.js
When no configuration for facets is provided, the API errors out
because the following is sent on the request body:
```
facets: {}
```
So for example, if you were to take the default example off the README guide, it actually errors out.
```
<SearchProvider
config={{
apiConnector: connector
}}
>
{() => (
<div className="App">
<Layout
header={<SearchBox />}
bodyContent={<Results titleField="title" urlField="nps_link" />}
/>
</div>
)}
</SearchProvider>
```
> Fix no configuration queries

- ADVANCED.md
- examples/sandbox/src/App.js
- packages/react-search-ui-views/src/Autocomplete.js
- packages/react-search-ui-views/src/SearchBox.js
- packages/react-search-ui-views/src/__tests__/Autocomplete.test.js
- packages/react-search-ui-views/stories/SearchBox.stories.js
- packages/react-search-ui/src/containers/SearchBox.js
Primarily updated suggestions so that you do not have to specify
a suggestion type on the component configuration.
So you can do this:
```jsx
<SearchBox
autocompleteSuggestions={{
sectionTitle: "Suggested Queries"
}}
/>
```
And don't necessarily have to know what type of query suggestions are coming back, as you did previously (although it is supported and valid syntax):
```jsx
<SearchBox
autocompleteSuggestions={{
documents: {
sectionTitle: "Suggested Queries"
}
}}
/>
```
Also provided some examples in the ADVANCED.md guide to help users get started
with the Autocomplete features.
> Simplified the usage of suggestions

- packages/react-search-ui-views/src/Result.js
- packages/react-search-ui-views/src/__tests__/Result.test.js
- packages/react-search-ui-views/src/__tests__/__snapshots__/Result.test.js.snap
- packages/react-search-ui-views/stories/Result.stories.js
- packages/react-search-ui-views/stories/ResultsContainer.stories.js
- packages/react-search-ui/src/containers/Result.js
**This is a breaking change.**
Updates the `Result` container component so that it no longer passes a `fields` prop to its view, only the `result` prop.  We believe this will lessen the confusion around `fields` vs `result` for developers wishing to implement their own view for the `Result` or `Results` container components.
Based on feedback from @qhoxie:
https://github.com/elastic/search-ui/pull/175#discussion_r275045206
https://github.com/elastic/search-ui/pull/175#discussion_r275047967
> Result container component no longer passes `fields` property to its views

- packages/search-ui-site-search-connector/README.md
- packages/search-ui-site-search-connector/src/__tests__/requestAdapter.test.js
- packages/search-ui-site-search-connector/src/__tests__/requestAdapters.test.js
- packages/search-ui-site-search-connector/src/requestAdapters.js
Add support in the SiteSearchAPIConnector for "any" filters. "none" remains an unsupported type.
> Added 'any' support for site search connector

- packages/react-search-ui/src/containers/SearchBox.js
- packages/react-search-ui/src/containers/__tests__/SearchBox.test.js
This prop was not being passed down to the view, so it was
not being used at all.
> Fix autocompleteView support

- examples/sandbox/package-lock.json
- packages/search-ui-app-search-connector/package-lock.json
- packages/search-ui-app-search-connector/package.json
- packages/search-ui-app-search-connector/src/AppSearchAPIConnector.js
- packages/search-ui-site-search-connector/src/SiteSearchAPIConnector.js
- packages/search-ui-site-search-connector/src/request.js
- packages/search-ui/README.md
This PR passes two additional headers back to Site Search an App Search for analytical purposes. These are ONLY passed when using one of these two connectors.
> Tag Swiftype requests with "search-ui" header

- examples/sandbox/src/App.js
- packages/react-search-ui-views/src/Autocomplete.js
- packages/react-search-ui-views/src/__tests__/__snapshots__/Autocomplete.test.js.snap
Swapped suggestions to appear on top of results in the default autocomplete view.
- Swapped suggestions to appear on top of results in the default autocomplete view.
- Updated the sandbox app to have a nicer looking autocomplete experience
Fixes #216
> Swapped autocomplete and autosuggest

- .gitignore
- ADVANCED.md
- packages/react-search-ui-views/src/ResultsPerPage.js
- packages/react-search-ui/src/containers/ResultsPerPage.js
- packages/react-search-ui/src/containers/__tests__/ResultsPerPage.test.js
- packages/react-search-ui/src/containers/__tests__/__snapshots__/ResultsPerPage.test.js.snap
ResultsPerPage component should have configurable options
* Added new prop `resultsPerPageOptions` to the `<ResultsPerPage />` component to configure results per page options.
* Documented `resultsPerPageOptions` prop usage.
* Added test case for`resultsPerPageOptions` 
#60
> ResultsPerPage component should have configurable options

- ADVANCED.md
- package.json
Documentation updates
- Added top level command for starting sandbox, for convenience
- Changed the recommendations for customizing component behavior to remove the `mapViewProps` function. It does not actually exist, and it's questionable whether it would actually be valuable. I added an alternate suggestion for overriding view props.
- I made much more thorough examples for autocomplete, because it seems to be hard for people to understand, currently.
Fixes #67
Fixes #100
> Documentation updates

- examples/sandbox/README.md
- examples/sandbox/src/App.js
By using the following command, you can now start the Sandbox site using Site Search, rather than App Search. It simply uses a different connector.
```
REACT_APP_SOURCE=SITE_SEARCH npm start
```
The plan is to publish this link, alongside https://search-ui-stable.netlify.com. So it would be something like https://search-ui-site-search-stable.netlify.com.
- Support Site Search in Sandbox application.
- Change default sort to Relevance for a better demo
> Site search connector demo

- packages/react-search-ui-views/src/MultiCheckboxFacet.js
- packages/react-search-ui-views/src/__tests__/MultiCheckboxFacet.test.js
- packages/react-search-ui/src/containers/Facet.js
- packages/react-search-ui/src/containers/__tests__/Facet.test.js
- packages/react-search-ui/src/containers/__tests__/__snapshots__/Facet.test.js.snap
Tweaked facet filter
- Showing a "no results" message
- Changed placeholder text to say "Filter" instead of "Search"
#131
> Updated facet filter

- packages/react-search-ui/src/withSearch.js
`withSearch` was waiting until CDM to render. This was making it
so that downstream components could not do certain things on mount,
or on `useEffect`.
Ex. Passing a ref to `SearchBox`, and focusing it on load
```
const searchField = useRef(null)
useEffect(() => {
searchField.current.focus()
}, [])
```
Without this change I made, this would error because searchField is null.
Haven't found a great way to test for this yet, as our version of Jest doesn't appear to execute `useEffect` in tests.
> Fixed withSearch CDM

- packages/react-search-ui-views/src/styles/themes/reference-ui/layouts/_layout.scss
Fixed layout issue in Results css when there are long values.
Before:
After:
Fixed layout issue in Results css when there are long values.
Fixes #265
> Fixed layout issue in Results css

- ADVANCED.md
- examples/sandbox/src/App.js
- packages/search-ui-app-search-connector/README.md
- packages/search-ui-app-search-connector/src/AppSearchAPIConnector.js
- packages/search-ui-app-search-connector/src/__tests__/AppSearchAPIConnector.test.js
- packages/search-ui-site-search-connector/README.md
- packages/search-ui-site-search-connector/src/SiteSearchAPIConnector.js
- packages/search-ui-site-search-connector/src/__tests__/SiteSearchAPIConnector.test.js
Made `additionalOptions` more useful.
Example:
```js
connector = new AppSearchAPIConnector({
beforeSearchCall: (existingSearchOptions, next) =>
next({
...existingSearchOptions,
group: { field: "title" }
})
});
```
- Updated hooks to amend, not just append
Previously the function simply merged in additional options to existing,
instead, it should allow you to amend the entire object, in case
there are some you'd like to remove.
- Made hooks work like middleware
Hook functions now accept a "next" parameter, to allow for adapting
the response as well, not just the incoming options.
- Separated out `additionalOptions` into 3 distinct hooks:
`beforeAutocompleteSuggestionsCall`
`beforeAutocompleteResultsCall`
`beforeSearchCall`
- Updated docs. Used jsdoc comments and generated markdown for …
> Additional options

- examples/sandbox/src/App.js
- packages/react-search-ui-views/src/Result.js
- packages/react-search-ui-views/src/__tests__/Result.test.js
- packages/react-search-ui-views/src/__tests__/__snapshots__/Result.test.js.snap
- packages/react-search-ui-views/src/types/FieldValueWrapper.js
- packages/react-search-ui-views/src/types/Result.js
- packages/react-search-ui/src/types/FieldValueWrapper.js
- packages/react-search-ui/src/types/Result.js
In our type definition for a "Result", we required it to have
a raw and snippet key:
```
{
raw: "",
snippet: ""
}
```
However, while this is the most common scenario, it's actually
technically possible to get other stuff back in a "Result".
For instance, when using the "group" feature in the App Search API,
you can get back a "_group" key in results. Or if you are using
this project with Elasticsearch, you might get a nested object back.
This schema was too arbitrarily strict. It's better to accept
anything here.
- Expanded results shown in the Sandbox application, just for a better demo and also for testing.
- Updated BOTH `Result.js` types, which are duplicated in two separate packages currently, but we should definitely find a way to consolidate in the future.
- Changed the `Result.js` …
> Loosened the "Result" object schema

- ADVANCED.md
- packages/react-search-ui-views/src/SearchBox.js
- packages/react-search-ui-views/src/SearchInput.js
- packages/react-search-ui-views/src/__tests__/SearchBox.test.js
- packages/react-search-ui-views/src/__tests__/view-helpers/appendClassName.test.js
- packages/react-search-ui-views/src/view-helpers/appendClassName.js
- packages/react-search-ui-views/stories/SearchBox.stories.js
- packages/react-search-ui/src/containers/SearchBox.js
Adding this allows for much simpler, targeted view customization.
Instead of having to deal with all of the Downshift plumbing and logic,
this lets you very easily target just the html.
For example, if you just want to hide the search button, or inject an icon, etc. This makes it much easier. CC @scottybollinger @zumwalt, this is something you had dealt with before.
```jsx
<SearchBox
inputView={({
getAutocomplete,
getButtonProps,
getInputProps
}) => (
<>
<div className="sui-search-box__wrapper">
<input
{...getInputProps({ placeholder: "I am thor" })}
/>
{getAutocomplete()}
</div>
<input {...getButtonProps()} />
</>
)}
```
See the ADVANCED.md updates for some more examples.
- Added a inputView option to SearchBox
#163
> Added a inputView option to SearchBox

- packages/search-ui-app-search-connector/src/responseAdapter.js
Since we have now loosened the Result schema to allow arbitrary fields (https://github.com/elastic/search-ui/pull/271), and the Result view now filters out those arbitrary fields, there is no reason to continue filtering out the `_meta` tag from App Search responses, which users may need (https://github.com/elastic/search-ui/issues/274).
This was a trivial change, and there were no tests for this case to begin with, so there are no tests to update either.
- Removed filtering of `_meta` from results on App Search API Responses
#274
> Allow meta

- packages/search-ui/src/SearchDriver.js
- packages/search-ui/src/__tests__/SearchDriver.test.js
This fixes an issue described in #279, where if you had components
nested under a `WithSearch`, that used state from `WithSearch` to
conditionally render, they would be one state update behind.
This is because the conditional components are initialized after
a state update on the higher level `WithSearch`, who's update was
triggered because they are subscribed to the driver's state.
When the nested component's constructor runs, they grab the most
recent state from the driver. However, the way the driver was set up,
subscriptions were executed BEFORE the driver's own state was updated.
Therefore, the nested component's state was being derived from the
outdated driver state.
- Changed driver to update own state before notifying subscriptions
Fixes #279
> Fixed issue with state not updating

- packages/react-search-ui-views/src/styles/themes/reference-ui/_base.scss
- packages/react-search-ui-views/src/styles/themes/reference-ui/modules/_variables.scss
Please compare the following two sites.
Without Roboto (new): https://search-ui-canary.netlify.com
With Roboto (current): https://search-ui-stable.netlify.com
The difference is very subtle, and I think this will be fine.
- Removed Roboto font and replaced with system styles suggested by @zumwalt 
Fixes: https://github.com/elastic/search-ui/issues/293
> Removed Roboto font

- ADVANCED.md
Per our quick Slack convo last Friday - I asked if the code sample in https://github.com/elastic/search-ui/pull/273/files#diff-f959751a4f181dc8bdc2673b10144d0fR323 was meant to have a different DOM structure than the default SearchBox. The answer was no, so I thought I'd update the docs example to match SearchBox :)
- Fixing inputView example to match Search UI's default SearchBox DOM structure
> Update inputView documentation example

- packages/react-search-ui-views/src/__tests__/layouts/Layout.test.js
- packages/react-search-ui-views/src/layouts/Layout.js
Initial question/ask:
> Do we want to consider allowing a custom `className` on Layout.js? We allow custom classNames on multiple other components (e.g. `SearchBox`, etc.) so it seemed a little odd that I couldn’t do something like `<Layout className="container container--wide">`.
- The Layout component should now pass/apply custom `className` props to the parent container.
Fixes #302
> Apply passed className prop to Layout component

- packages/react-search-ui-views/README.md
- packages/react-search-ui/README.md
- packages/search-ui-app-search-connector/README.md
- packages/search-ui-site-search-connector/README.md
- packages/search-ui/README.md
2 things I noticed when viewing the package on NPM is that there is the big notice about being in Beta, which I don't think we want any longer. And also, when you're looking at one of these individually, it's easy to miss the context that they are part of a larger project.
- Removed the "beta" warning, since these are find to
use in production.
- Added a link to the main project, so it's clear from the npm
descriptions that these are a part of a larger project.
> Updated README notices.

- packages/react-search-ui-views/src/ResultsPerPage.js
- packages/react-search-ui-views/src/__tests__/__snapshots__/ResultsPerPage.test.js.snap
- packages/react-search-ui-views/src/styles/themes/reference-ui/components/_result.scss
- packages/react-search-ui-views/src/styles/themes/reference-ui/components/_select.scss
- packages/react-search-ui-views/src/styles/themes/reference-ui/layouts/_layout.scss
- packages/react-search-ui-views/stories/ResultsPerPage.stories.js
- packages/react-search-ui/src/containers/__tests__/__snapshots__/ResultsPerPage.test.js.snap
After removing the Roboto font, there was an issue with the
ResultPerPage dropdown, where it was too narrow for the font and
was being squashed down to an ellipses.
Additionally, there was an issue where the box shadow of the
dropdown was being cut off due to a change made in #266. I moved
the styles from that change to be more targeted to fix this.
Before:
After:
> Fixed a CSS bug

- packages/react-search-ui-views/src/PagingInfo.js
- packages/react-search-ui-views/src/__tests__/PagingInfo.test.js
- packages/react-search-ui-views/src/__tests__/__snapshots__/PagingInfo.test.js.snap
- packages/react-search-ui-views/stories/PagingInfo.stories.js
Caught this issue while doing some accessibility testing! It's pretty minor but I think it'll reduce confusion slightly.
(Notice 41 - **80**, when the results max/cap out at 59) 
(Using the correct results max)
- Adds a `Math.min()` check to obtain the lesser of `end` and `totalResults`
> Fix issue where paging info would show a higher end than possible

- packages/react-search-ui-views/src/MultiCheckboxFacet.js
- packages/react-search-ui-views/src/__tests__/__snapshots__/MultiCheckboxFacet.test.js.snap
- packages/react-search-ui-views/src/styles/themes/reference-ui/components/_multi-checkbox-facet.scss
This is a quick semantic markup change which enhances many screen readers' ability to associate multiple checkbox groups with its parent group label.
Notice how California now reads out the parent "States" label, giving more context to keyboard tabbing users.
^ Posting for general edification - note how the parent `legend` is only read out when the user tabs into the **first** input within the `fieldset` group, and is not read out again when tabbing to other items within the group. This is great behavior for context while not becoming repetitive.
- Changes MultiCheckboxFacet markup from `div`s to `fieldset`/`legend` tags.
> [a11y] More accessible MultiCheckboxFacets

- packages/react-search-ui-views/src/styles/themes/reference-ui/components/_results-per-page.scss
I noticed this when working on #334 and thought I'd push out a separate fix for this (to keep the PRs clean/atomic).
When PagingInfo is on a small enough screen or has a long enough Search Term to span multiple lines, the vertical alignment on ResultsPerPage's dropdown gets all wonky (see below screenshot).
**Before (left) vs. After (right):**
- Adds CSS fixing vertical alignment on ResultsPerPage's react-select dropdown
> Fix ResultsPerPage vertical alignment on mobile

- packages/react-search-ui-views/src/styles/themes/reference-ui/components/_result.scss
While working on #334, I noticed the `max-height` being set on Result card bodies was resulting in content being sometimes misleadingly cut off on mobile devices. I propose removing this entirely and letting cards remain whatever height they're at.
- Removes max-height, overflow, and other associated/unnecessary CSS from `.sui-result__details`
> Remove max-height+scrolling on Result card body

- packages/react-search-ui-views/src/__tests__/layouts/LayoutSidebar.test.js
- packages/react-search-ui-views/src/__tests__/layouts/__snapshots__/Layout.test.js.snap
- packages/react-search-ui-views/src/__tests__/layouts/__snapshots__/LayoutSidebar.test.js.snap
- packages/react-search-ui-views/src/layouts/Layout.js
- packages/react-search-ui-views/src/layouts/LayoutSidebar.js
- packages/react-search-ui-views/src/layouts/SidebarToggle.js
- packages/react-search-ui-views/src/styles/themes/reference-ui/layouts/_layout.scss
- packages/react-search-ui-views/src/styles/themes/reference-ui/modules/_variables.scss
From our Slack discussion:
> I thought it'd be a shame to ship 1.0 without very basic mobile functionality - so I spiked out a quick attempt at a mobile toggle for our sidebar/filters. I'm hoping that it's a good enough start for the upcoming release and that we can continue to iterate on it for 2.0+
1. Adds a new internal [LayoutSidebar](https://github.com/elastic/search-ui/pull/334/files#diff-0433fdec156966cc8e783042c78eff6c) component + styling which:
- handles conditionally rendering show/hide toggle buttons
- makes the filter sidebar a scrollable sticky flyout on mobile
- does not display toggle buttons if there is no content in the sidebar
Note that for developers that utilize `<Layout>` but are completely rolling their own styles - they will not inherit this mobile UX as a result, …
> Add basic/MVP mobile UX for layout sidebar

- packages/react-search-ui-views/src/styles/themes/reference-ui/components/_multi-checkbox-facet.scss
- packages/react-search-ui-views/src/styles/themes/reference-ui/components/_search-box.scss
This fixes some very minor cross-browser Edge CSS issues that I noticed while testing Search UI's sandbox example in Browserstack.
**Before (left) vs. After (right):**
(Weird squashing/padding on right appeared to be due to flexbox & shrinking)
(Very subtle sans-serif vs. Segoe font in "Filter states")
- Fixes font family on SearchBox's text/button input not inheriting correctly on Edge
- Fix SearchBox's "Search" button being squashed on Edge
- Fixes font family on Search Filters input not inheriting correctly on Edge
> Fix misc. Edge cross-browser styling issues

- CONTRIBUTING.md
- examples/elasticsearch/package-lock.json
- examples/sandbox/package-lock.json
- packages/package-lock.json
- packages/package.json
- packages/react-search-ui-views/babel.config.js
- packages/react-search-ui-views/package-lock.json
- packages/react-search-ui-views/package.json
- packages/react-search-ui-views/src/index.js
- packages/react-search-ui/babel.config.js
- packages/react-search-ui/package-lock.json
- packages/react-search-ui/package.json
- packages/search-ui-app-search-connector/babel.config.js
- packages/search-ui-app-search-connector/package-lock.json
- packages/search-ui-app-search-connector/package.json
- packages/search-ui-app-search-connector/src/index.js
- packages/search-ui-site-search-connector/babel.config.js
- packages/search-ui-site-search-connector/package-lock.json
- packages/search-ui-site-search-connector/package.json
- packages/search-ui-site-search-connector/src/index.js
- packages/search-ui/babel.config.js
- packages/search-ui/package-lock.json
- packages/search-ui/package.json
- packages/search-ui/src/index.js
`@babel/polyfill` was a dependency in this project. This was a pretty crazy headache, as it was a runtime dependency (as opposed to a build time, dev dependencies) that actually goes out and Polyfills a number of global APIs, like `Promise`, `Map`, etc, which is very intrusive and there is a lot of potential for conflict there. It's especially bad since this is a library, and you would *not* expect a library to do that.
In Babel's docs, they actually outline two methods for handling these globals. The first is the Polyfill, which they advise against for the libraries. The second, is https://babeljs.io/docs/en/babel-plugin-transform-runtime, which they DO recommend for libraries.
The approach the plugin takes is to replace globals like "Promise.all" etc with helpers from the …
> Removed babel polyfill

- .circleci/config.yml
- CONTRIBUTING.md
- package.json
I kept messing up dependency installs (documented [here](https://github.com/elastic/search-ui/blob/master/CONTRIBUTING.md#installing-dependencies)) and thought I'd make it more idiot-proof for future me 😄
Now instead of having to run 3 separate install commands, just running the default `npm install`/`yarn install` commands will also trigger installing `packages/package.json` and `lerna bootstrap`.
- Add a postinstall script that auto-installs subfolder dependencies
- Update CircleCI
- Update docs
> Automatically bake in subfolder installs into `npm install`

- packages/react-search-ui-views/src/PagingInfo.js
- packages/react-search-ui-views/src/__tests__/PagingInfo.test.js
- packages/react-search-ui-views/src/__tests__/__snapshots__/PagingInfo.test.js.snap
- packages/react-search-ui/src/containers/PagingInfo.js
- packages/react-search-ui/src/containers/__tests__/PagingInfo.test.js
It's https://github.com/elastic/search-ui/pull/318 redux! 😅 When working in `react-search-ui`'s PagingInfo component, I finally got my mind out of "views" mode and realized that we need to fix the issue at the container level and not the view level - since we're still sending the incorrect "end" to users using custom views. Also, the a11y announcement (that I'm working on) needs the correct numbers as well.
- Removes old `Math.min()` code and moves the `totalResult` check logic to `PagingInfoContainer` instead
- Updates tests
> More robust fix for PagingInfo showing a higher end than possible

- packages/search-ui/src/__tests__/SearchDriver.test.js
- packages/search-ui/src/test/helpers.js
I found this issue while writing tests for the upcoming a11y SearchDriver work.
1. In [SearchDriver.test.js, line 71](https://github.com/constancecchen/search-ui/blob/fd4add80ab82fcc4a688b3e1b7ea2ff0cbdb5dd3/packages/search-ui/src/__tests__/SearchDriver.test.js#L71), change `requestId` to `67890` (or any other string)
2. Add `console.log(stateAfterCreation)` to the end of this test
3. Notice that the test now fails and the console log returns the [default `resultId: "12345"`](https://github.com/constancecchen/search-ui/blob/fd4add80ab82fcc4a688b3e1b7ea2ff0cbdb5dd3/packages/search-ui/src/test/helpers.js#L20) searchResponse still
1. Pull down this branch.
2. Add `console.log(stateAfterCreation)` to the end of [this test](https://github.com/constancecchen/search-ui/blob/fd4add80ab82fcc4a688b3 …
> Fix non-working mockSearchResponse in SearchDriver test

- CONTRIBUTING.md
This PR comes as a result of [a conversation in Gitter](https://gitter.im/elastic-search-ui/community?at=5d336ebfec5abe7bbc1bb4c0) originally reported by @compuroad.
> ⚠️ **NOTE**:
> None of this applies to developers who are **using** and not **developing** search-ui. This error does not come up when simply installing the search-ui package via npm. This only applies to developers who clone the repo and are attempting to develop search-ui locally.
When I attempted to [reproduce the issue](https://gitter.im/elastic-search-ui/community?at=5d35d6ff35e05c0993806f98) locally on my Windows 10 machine, I found that the issue was not after all with either `cd` or `&&` on PowerShell, but with our `bin/` unix executables (located in all lerna packages). Here's a copy of the full error:
```console
> …
```
> Add contributing clarification for Windows developers

- packages/react-search-ui-views/src/PagingInfo.js
- packages/react-search-ui-views/src/__tests__/__snapshots__/PagingInfo.test.js.snap
- packages/react-search-ui/src/containers/__tests__/PagingInfo.test.js
- packages/react-search-ui/src/containers/__tests__/__snapshots__/PagingInfo.test.js.snap
When a user searches for an empty string, the UI showing the pagination information looks a little odd. It looks much better when we remove the text "for". 
* Removes "for" from the text displaying the pagination information. 
#337
> Modifies the way empty string searches are displayed in the Pagination info

- packages/search-ui-app-search-connector/package.json
- packages/search-ui-app-search-connector/src/AppSearchAPIConnector.js
- packages/search-ui-app-search-connector/src/__tests__/AppSearchAPIConnector.test.js
This PR updates the App Search connector to the latest App Search API client, which is now published under @elastic/app-search-javascript
Closes https://github.com/elastic/search-ui/issues/385
> Updated to the latest App Search API client

- packages/react-search-ui-views/src/BooleanFacet.js
- packages/react-search-ui-views/src/__tests__/BooleanFacet.test.js
- packages/react-search-ui-views/src/__tests__/__snapshots__/BooleanFacet.test.js.snap
If a user filters the results to the point where there are no
"true" values in a facet, then the BooleanFacet should hide itself.
Instead, the component was currently erroring out.
Relates to: https://github.com/elastic/search-ui/pull/383
> Fixed "no true options" case for BooleanFacet

- ADVANCED.md
- packages/search-ui/src/SearchDriver.js
- packages/search-ui/src/__tests__/SearchDriver.test.js
- packages/search-ui/src/__tests__/actions/trackClickThrough.test.js
When `alwaysSearchOnInitialLoad` is set to `true`, the `SearchDriver` will do an initial search, even if `searchTerm` and/or `filters` is empty.
- Added `alwaysSearchOnInitialLoad` to the config options of `SearchDriver` that defaults to false
- Added a check to the constructor of `SearchDriver`. The check is at the same place as the original `should we do an initial search is` (`SearchDriver.js` line 180)
- Added two tests to verify that `alwaysSearchOnInitialLoad` behaves as expected
- Added documentation for the option `alwaysSearchOnInitialLoad` to `ADVANCED.md`
#194
> Initial search

- packages/react-search-ui-views/src/SearchBox.js
- packages/react-search-ui-views/src/__tests__/SearchBox.test.js
- packages/react-search-ui-views/src/__tests__/__snapshots__/SearchBox.test.js.snap
This allows us to add a button in our custom `InputView` which calls `clearSelection`:
https://github.com/downshift-js/downshift#actions
Pass down `downshiftProps` to `InputView`.
None
> Pass down downshift props to `InputView`

- packages/search-ui-site-search-connector/src/SiteSearchAPIConnector.js
In the SiteSearchAPIConnector, we were warning users not to use tags
for click through tagging, even though it was not actually in use.
This was due to a simple truthy check. Since tags are an array, the
check was passing. We are now checking length.
Fixes #405
> Bugfix: Fix SS console warning when no tags

- packages/search-ui/src/__tests__/queryString.test.js
- packages/search-ui/src/queryString.js
This PR fixes an issue with rehydrating the search state from an URL. If more than 20 filters (from the same filter) is applied, the page cannot be refreshed.
**Steps to reproduce the issue**
- Open the demo - https://search-ui-stable.netlify.com/
- Add more than 20 filters on "State"
- Wait a second for the URL to sync
- Refresh the page - an error will display "An unexpected error occurred: e.values.map is not a function"
The [qs lib](https://github.com/ljharb/qs) has a default arrayLimit of 20 when it parses an URL. For arrays larger than 20 it creates an object for performance reasons.
However, I suspect that we still want an array instead of an object.
_I din't create an issue first, but thought that this was small enough to go straight to a PR._
> Support rehydrating search state from URL when more than 20 filters are applied

- packages/react-search-ui/package.json
- packages/search-ui/package.json
Usage was removed in https://github.com/elastic/search-ui/pull/442,
this commit removes it as a dependency since it is no longer used.
> Removed dependency on debounce-fn

- packages/search-ui/src/SearchDriver.js
- packages/search-ui/src/URLManager.js
- packages/search-ui/src/__tests__/SearchDriver.test.js
- packages/search-ui/src/__tests__/URLManager.test.js
Currently, when showing search results on page load, an extra history
event is added to history, causing a few issues, including the
inconvenience on users of having to press the back button twice to get
back to where they were originally.
The fix is to simply use a browser history "replace" instead of "push"
on the any queries happening on page load.
This PR is based on the following PR:
https://github.com/elastic/search-ui/pull/443
Fixes Fixes https://github.com/elastic/search-ui/issues/434
> fix: Search-UI smart url forces extra history push

- packages/react-search-ui-views/src/__tests__/__snapshots__/Paging.test.js.snap
- packages/search-ui/src/SearchDriver.js
- packages/search-ui/src/__tests__/SearchDriver.test.js
- packages/search-ui/src/test/helpers.js
applicable).
This change uses different sequencers for different types of requests. This might cause a race condition that is described by issue #452. 
- Initialize two sequencers one for autocomplete and other for search.
- Update snapshot for Paging.test
#452
> Use different sequencers for autocomplete and search request

- packages/react-search-ui-views/src/__tests__/MultiCheckboxFacet.test.js
- packages/react-search-ui-views/src/__tests__/SingleLinksFacet.test.js
- packages/react-search-ui-views/src/__tests__/SingleSelectFacet.test.js
- packages/react-search-ui-views/src/__tests__/__snapshots__/MultiCheckboxFacet.test.js.snap
- packages/react-search-ui-views/src/__tests__/__snapshots__/SingleLinksFacet.test.js.snap
- packages/react-search-ui-views/src/__tests__/__snapshots__/SingleSelectFacet.test.js.snap
- packages/react-search-ui-views/src/view-helpers/getFilterValueDisplay.js
- packages/react-search-ui-views/stories/MultiCheckboxFacet.stories.js
- packages/react-search-ui-views/stories/SingleLinksFacet.stories.js
- packages/react-search-ui-views/stories/SingleSelectFacet.stories.js
Values like `0` or `false` were being thrown out and an empty string
was being shown instead. This fixes that in all facet views.
Fixes #453
> Facets should show string value for falsy values

- packages/react-search-ui-views/package.json
CSS should be marked as having side effects in package.json. Otherwise,
an import like...
```
import "@elastic/react-search-ui-views/styles.css"
```
... will be viewed by tree shaking as an unused import. By using ...
```
sideEffects: [
"*.css*
]
```
... we ensure that css imports will not be dropped by tree shaking.
For reference: https://github.com/gatsbyjs/gatsby/issues/19446
I set up a project to illustrate this problem: https://github.com/JasonStoltz/example-for-gatsby-issue
After pulling the project down, run:
```
npm install
npx gatsby build
npx gatsby serve
```
The resultant screen should be styled with search UI styles.
For comparison, you can revert the latest [commit](https://github.com/JasonStoltz/example-for-gatsby-issue/commit/f05cd5d4966cdde4c6e5baec07d1d1adf0965fef) in …
> Changed sideEffects in package.json for CSS

- packages/react-search-ui/package.json
- packages/react-search-ui/react-search-ui.d.ts
Added TypeScript typings for react-search-ui
- Added react-search-ui.d.ts to the react-search-ui package
- Exported all classes except for helper types and classes in the `types` folder that had duplicate names in `containers`: `Facet` and `Result`. Those are renamed FacetT and ResultT and not exported.
- https://github.com/elastic/search-ui/issues/289
Associated PR in DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41605
> Add react-search-ui typings

- .github/stale.yml
https://probot.github.io/apps/stale/
This is to help keep the backlog manageable and to help ensure
the best and most important work is bubbled up to the top of the backlog
to address.
I like their philosophy:
https://github.com/probot/stale#is-closing-stale-issues-really-a-good-idea
> Is closing stale issues really a good idea?
> In an ideal world with infinite resources, there would be no need for this app.
> But in any successful software project, there's always more work to do than people to do it. As more and more work piles up, it becomes paralyzing. Just making decisions about what work should and shouldn't get done can exhaust all available resources. In the experience of the maintainers of this app—and the hundreds of other projects and organizations that use it—focusing on …
> Enabling Probot to close stale issues.

- bin/sandbox
- examples/sandbox/README.md
- package.json
- packages/react-search-ui-views/bin/test
- packages/react-search-ui-views/package.json
- packages/react-search-ui/bin/test
- packages/react-search-ui/package.json
- packages/react-search-ui/src/SearchProvider.js
- packages/react-search-ui/src/__tests__/SearchProvider.test.js
- packages/react-search-ui/src/__tests__/SearchProvider_withMocks.test.js
This PR changes SearchProvider to use hooks in advance of fixing https://github.com/elastic/search-ui/issues/464.
In order for hooks to work within the local sandbox environment during
development, we needed to resolve an "invalid hook call" error.
A number of solutions are proposed here:
https://reactjs.org/warnings/invalid-hook-call-warning.html
In our case, the error stemmed from the fact that we link our
dependencies from sandbox to our packages. To resolve that, we
need to also link the `react` we use in our packages to the react we use
in the sandbox. 😵 
I chose to add that linking automatically so that it happens
when running `npm run sandbox`, to make it seamless for developers.
Since that unfortunately causes issues running tests, as a result, I also added a new check
to tests to …
> Switched SearchProvider to be a functional component with hooks

- packages/search-ui/src/SearchDriver.js
- packages/search-ui/src/__tests__/SearchDriver.test.js
- packages/search-ui/src/__tests__/helpers.test.js
- packages/search-ui/src/helpers.js
Faceting was not working when a global filter was applied via searchQuery configuration. This fixes that.
This logic will prefer filters chosen in the UI to filters specified in searchQuery config if there is a conflict.
Ex.
```
<SearchProvider config={{
searchQuery: {
filters: [{ field: "world_heritage_site", values: ["true"] }],
}}>
</SearchProvider>
```
You can apply the above and still use filters.
You can see that in action in the gif below. There are only 14 results since the data is filtered by "world_heritage_site". There is usually > 50. You can see that facet filters will still work.
Fixes https://github.com/elastic/search-ui/issues/470
> Fixed searchQuery config for global filters

- packages/react-search-ui/src/SearchProvider.js
- packages/react-search-ui/src/__tests__/SearchProvider.test.js
- packages/search-ui/src/SearchDriver.js
This allows Search Configuration to be changed after mounting SearchProvider. This unlocks uses cases like:
- Dynamically changing the `facets` available in a Search Experience based on user selections
- Dynamically changing `search_fields` based on users selection (Imagine an experience where you have a toggle that says something like "Search In" with selection of "title", "user name", etc.".
- Dynamically changing the `result_fields` that are displayed
This works for the configurations `autocompleteQuery` and `searchQuery` on the `SearchProvider` configuration.
```jsx
function App() {
const [searchQuery, setSearchQuery] = useState({
facets : /*List of facets*/
});
const newSearchQuery = {
facets : /*List of NEW facets*/
}
return (
<SearchProvider config={ searchQuery }>
<button …
```
> Dynamic Search Configuration

- packages/react-search-ui-views/src/BooleanFacet.js
- packages/react-search-ui-views/src/__tests__/__snapshots__/BooleanFacet.test.js.snap
#482  Description
Make sure that checkbox shows checked/unchecked depending on value of `isSelected` in case filter value is set via function call rather than via clicking the checkbox.
#490
> Fix boolean facet check status

- packages/search-ui/src/SearchDriver.js
- packages/search-ui/src/__tests__/SearchDriver.test.js
They were being passed through to App Search which was causing
a 400 error.
https://github.com/elastic/search-ui/issues/489
> Fixed conditional Facets

- packages/search-ui-app-search-connector/src/__tests__/responseAdapter.test.js
- packages/search-ui-app-search-connector/src/responseAdapter.js
There is a known issue in the App Search API in which a search response
may return a total page count of over 100, even thought the API can
only page up to page 100.
This will break Search UI's paging, which assumes that if the API
says there are 1000 pages, that they can all be paged through.
This commit rewrites the response in the App Search Connector to cap
pages to 100.
Before:
After:
Fixes https://github.com/elastic/search-ui/issues/485
> Limited App Search paging to 100 results

- packages/react-search-ui-views/babel.config.js
- packages/react-search-ui/babel.config.js
- packages/search-ui-app-search-connector/babel.config.js
- packages/search-ui-site-search-connector/babel.config.js
- packages/search-ui/babel.config.js
It appears that babel config no longer accepts a string value of
"false", and requires an actual boolean.
I know this is not very DRY but I prefer it to having to jump out of a config file into a separate helper file.
> Fixed JS build and CI

- packages/react-search-ui-views/package.json
- packages/react-search-ui/package.json
I accidentally introduced a hard dependency on `react` to the `@elastic/react-search-ui` and `@elastic/react-search-ui-views` libraries.
If a consuming project is using a different version of React, this will cause a version conflict error.
I simply removed the dependency in order to fix this. I plan to publish this in a 1.4.1 patch.
For example, when I updated the search-ui 1.4.0 in the reference ui, I received the following error:
If you reference that error on the React documentation site, it tells you this can be caused by two separate versions of React conflicting.
The following confirms that:
```
→npm ls react
app-search-reference-ui-react@1.2.0 /Users/jasonstoltzfus/workspace/app-search-reference-ui-react
→npm ls react
app-search-reference-ui-react@1.2.0 …
```
> Removed React dependency from packages

- examples/elasticsearch/functions/search.js
Users who use this demo may often times be pointing at an instance
that has a self-signed certificate. For the sake of the demo, we simply
trust all certificates.
Additionally, the error message printed by our Netlify function was
not helpful. This should resolve that.
Fixes https://github.com/elastic/search-ui/issues/497
> Fix errors on Elasticsearch Demo

- packages/react-search-ui-views/package.json
For some reason, CI started failing due to the following error:
Cannot find module 'core-js-pure/features/url' from 'getUrlSanitizer.test.js'
@elastic/react-search-ui-views:       1 | import { getUrlSanitizer } from "../../view-helpers";
@elastic/react-search-ui-views:     > 2 | import URL from "core-js-pure/features/url";
@elastic/react-search-ui-views:         | ^
This seems like it should have been an error from the start, as we were
missing core-js-pure from devDependencies.
It may have previously been a transitive dependency and has since
been removed. Regardless, it should have been a hard dependency
from the start, so I've added it to our list of devDependencies which
appears to have fixed the issue.
> Fixed CI and Specs

- packages/search-ui-app-search-connector/src/AppSearchAPIConnector.js
- packages/search-ui-site-search-connector/src/SiteSearchAPIConnector.js
- packages/search-ui-site-search-connector/src/request.js
- packages/search-ui/README.md
This PR removes the 'swiftype_' prefixed headers on API calls for the App Search and Site Search connectors.
These were originally introduced when App Search and Site Search were purely SaaS products, for our own analytical purpose. These are no longer used or needed by us (Elastic).
Since this causes complications in the build as seen in #539, I'd rather just remove them entirely.
Since these headers were for internal use, I don't consider this a breaking change.
Removed `x-swiftype-integration` and `x-swiftype-integration-version` headers.
Fixes #539
Alternative to #572
> Removed 'swiftype_' headers

- README.md
I would like to shut down our gitter site in favor of Elastic's discuss forum.
Primarily because:
1. The App Search team monitors the Discuss forums so users are more likely to get a timely response.
2. Gitter is primarily being used for Q&A, and less discussion, which Discuss is better suited to.
> [Proposal] Shut down our gitter site

- examples/sandbox/package.json
- examples/sandbox/src/App.js
- examples/sandbox/src/Router.js
- examples/sandbox/src/WorkplaceSearch.js
- examples/sandbox/src/configurations/WorkplaceSearch.js
- examples/sandbox/src/index.js
- yarn.lock
This PR separates sandbox into Workplace Search sandbox and everything else.
Workplace search sandbox is now available at `http://localhost:3000/workplace-search/`:
I didn't do much work on facets, just added a couple to demonstrate the Ws-specific data.
Best to view changes with whitespace hidden.
> Extract Workplace Search sandbox to a different page

- packages/search-ui/src/SearchDriver.ts
- packages/search-ui/src/__tests__/SearchDriver.test.ts
There is an off-by-one error when calculating the pageEnd of a resultset.
- Fixed incorrect calculation of pageEnd
> Fix off-by-one error in results pagination state.

- examples/sandbox/src/pages/workplace-search/index.css
- examples/sandbox/src/pages/workplace-search/index.js
- packages/search-ui-workplace-search-connector/src/WorkplaceSearchAPIConnector.ts
- packages/search-ui/src/SearchDriver.ts
- packages/search-ui/src/__tests__/SearchDriver.test.ts
- packages/search-ui/src/test/helpers.ts
This PR adds a header to the Workplace Search sandbox and implements a logout button.
Clicking on the logout button does two things:
1) Removes the token from the localstorage
2) Redirects user to [ent-search]/logout which invalidates the ent-search session and redirects to [kibana]/logout which invalidates the kibana session
The logout method was implemented on the Workplace Search connector and passed as an action to search-ui core actions.
https://user-images.githubusercontent.com/11838280/158480315-7cb9d316-6bcb-41dc-af72-95cef9227a33.mp4
> Workplace Search header and logout

- examples/sandbox/src/pages/elasticsearch/index.js
- packages/react-search-ui/src/containers/Facet.tsx
- packages/react-search-ui/src/containers/__tests__/Facet.test.tsx
- packages/react-search-ui/src/containers/__tests__/__snapshots__/Facet.test.tsx.snap
- packages/search-ui-elasticsearch-connector/package.json
- packages/search-ui-elasticsearch-connector/src/handlers/search/Configuration.ts
- packages/search-ui-elasticsearch-connector/src/handlers/search/__tests__/Configuration.test.ts
- packages/search-ui/src/types/index.ts
- yarn.lock
Supports the ability to sort facet values alphabetically. Configuration is consistent with the facet field configuration API. Also involved building the feature into Searchkit https://github.com/searchkit/searchkit/pull/1092.
Also fixed an annoying issue where the search placeholder for Facet is now using the label value, not the field. Was putting in "states.keyword" in the placeholder and really annoyed me 😂 
```javascript
facets: {
"world_heritage_site.keyword": { type: "value", sort: "count" },
"states.keyword": { type: "value", size: 30, sort: "value" } // using the sort attribute
}
```
> Elasticsearch-connector: Facet Value Sort Feature 

- packages/search-ui-workplace-search-connector/README.md
1) Added the link to the sandbox example, 
2) Updated a couple links
3) Added description for the new "logout" action
4) Mentioned that `beforeAutocompleteSuggestionsCall` is not supported by Workplace Search
> Update Workplace Search connector docs

- packages/react-search-ui-views/bin/build-css
- packages/react-search-ui-views/package.json
- packages/react-search-ui-views/src/styles/themes/reference-ui/components/_paging.scss
Two changes:
- replacing node-sass for sass: https://github.com/elastic/search-ui/pull/656
- yarn workspaces https://github.com/elastic/search-ui/pull/635
have caused two regressions + changes in this PR:
- sass is now generating css sourcemap files with file paths that do not exist in the packaged library. Fix is to switch off sourcemap generation so behaves the same as node-sass.
- rc-pagination css code was not included in the bundled css file. yarn workspaces has changed the location of the rc-pagination library (now in the node_modules root). Fix was to update the path to the css file. Ive also moved the positioning of the import outside the import block and removed the postcss-import task as the import now happens in sass execution.
> disable sourcemaps + update rc-pagination css

- packages/react-search-ui/src/__tests__/SearchProvider.test.tsx
- packages/react-search-ui/src/__tests__/WithSearchRenderProps.test.tsx
- packages/search-ui-app-search-connector/src/AppSearchAPIConnector.ts
- packages/search-ui-elasticsearch-connector/src/index.ts
- packages/search-ui/src/test/helpers.ts
- packages/search-ui/src/types/index.ts
It is only needed in the Workplace Search connector and it's possible that it will be removed from that interface at some point.
This is a follow-up to https://github.com/elastic/search-ui/pull/682, where the state property was added to APIConnector interface.
> Make state property on APIConnector interface optional

- examples/sandbox/src/pages/elasticsearch/index.js
- packages/search-ui-elasticsearch-connector/README.md
- packages/search-ui-elasticsearch-connector/src/handlers/autocomplete/__tests__/results.test.ts
- packages/search-ui-elasticsearch-connector/src/handlers/autocomplete/index.ts
- packages/search-ui-elasticsearch-connector/src/handlers/autocomplete/results.ts
- packages/search-ui-elasticsearch-connector/src/handlers/search/Configuration.ts
- packages/search-ui-elasticsearch-connector/src/handlers/search/__tests__/Configuration.test.ts
- packages/search-ui-elasticsearch-connector/src/handlers/search/__tests__/index.test.ts
- packages/search-ui-elasticsearch-connector/src/handlers/search/index.ts
- packages/search-ui-elasticsearch-connector/src/index.ts
- packages/search-ui/src/types/index.ts
Search Fields were explicitly specified via the connectors constructor options. With this change, it now uses Search UI's configuration of search_fields.
> elasticsearch connector to use search_fields

- packages/search-ui/src/SearchDriver.ts
- packages/search-ui/src/__tests__/SearchDriver.test.ts
The type definition is wrong. As `next()` will not work without the required params.
Add required params to Typescript type definition of `onSearchHook`, `onAutocompleteHook`.
Related #689, @joemcelroy
> Fix Typescript type definition of `onSearchHook`, `onAutocompleteHook`

- docs/examples-search-as-you-type.mdx
- docs/nav-searchui.docnav.json
- examples/sandbox/src/Router.js
- examples/sandbox/src/pages/root.js
- examples/sandbox/src/pages/search-as-you-type/index.js
This PR adds a new example page to sandbox and docs.
New sandbox page:
https://user-images.githubusercontent.com/11838280/167008950-5561d532-a495-45bb-ac57-8a9ea474db8c.mp4
New docs page (the embed is not working yet since the code is still in PR):
I put the new section below the tutorials since users need to go through a tutorial first and then follow the examples.
> Add search-as-you-type example 

- PUBLISHING.md
- docs/overview.mdx
This PR changes all our links to stable demos from Netlify to Codesandbox pointing at our GitHub repo.
Also updated the Overview page in docs to embed a live demo:
https://user-images.githubusercontent.com/11838280/166825932-2083380b-8f67-4af7-85f1-a602bf467d28.mp4
> Use codesandbox demos instead of netlify

- docs/examples-search-as-you-type.mdx
- docs/guides-customizing-styles-and-html.mdx
- examples/sandbox/src/Router.js
- examples/sandbox/src/pages/customizing-styles-and-html/ClearFilters.js
- examples/sandbox/src/pages/customizing-styles-and-html/custom.css
- examples/sandbox/src/pages/customizing-styles-and-html/index.js
- examples/sandbox/src/pages/root.js
This PR adds a new example to sandbox. 
The example was copied from already existing codesandbox: https://codesandbox.io/s/search-ui-customize-html-and-styles-demo-30v93e?file=/src/App.tsx
https://user-images.githubusercontent.com/11838280/167201219-4b64adfa-9518-4a06-9df0-927effe3844d.mp4
In the docs, I decided to add it inline rather than creating a separate page for it. Having everything in one place seems more convenient to read.
> Example customizing styles and html

- docs/examples-search-bar-in-header.mdx
- docs/nav-searchui.docnav.json
Now when the sandbox is working, I'm adding an example to docs site:
> Add docs for search bar in header

- packages/react-search-ui-views/src/Autocomplete.tsx
- packages/react-search-ui-views/src/BooleanFacet.tsx
- packages/react-search-ui-views/src/MultiCheckboxFacet.tsx
- packages/react-search-ui-views/src/ResultsPerPage.tsx
- packages/react-search-ui-views/src/SearchBox.tsx
- packages/react-search-ui-views/src/SingleLinksFacet.tsx
- packages/react-search-ui-views/src/SingleSelectFacet.tsx
- packages/react-search-ui-views/src/Sorting.tsx
- packages/react-search-ui-views/src/__tests__/__snapshots__/Autocomplete.test.tsx.snap
- packages/react-search-ui-views/src/__tests__/__snapshots__/BooleanFacet.test.tsx.snap
- packages/react-search-ui-views/src/__tests__/__snapshots__/MultiCheckboxFacet.test.tsx.snap
- packages/react-search-ui-views/src/__tests__/__snapshots__/ResultsPerPage.test.tsx.snap
- packages/react-search-ui-views/src/__tests__/__snapshots__/SingleLinksFacet.test.tsx.snap
- packages/react-search-ui-views/src/__tests__/__snapshots__/Sorting.test.tsx.snap
- packages/react-search-ui/src/containers/__tests__/__snapshots__/ResultsPerPage.test.tsx.snap
- packages/react-search-ui/src/containers/__tests__/__snapshots__/Sorting.test.tsx.snap
Closes https://github.com/elastic/enterprise-search-team/issues/2155
That will help recognize user interactions in the APM dashboard
Example:
Instead of "Click - input" we will now show "Click - search button"
> Add data-transaction-name to interactive elements

- docs/api-connectors-elasticsearch.mdx
- packages/search-ui-elasticsearch-connector/src/handlers/autocomplete/__tests__/index.test.ts
- packages/search-ui-elasticsearch-connector/src/handlers/autocomplete/index.ts
- packages/search-ui-elasticsearch-connector/src/handlers/search/Configuration.ts
- packages/search-ui-elasticsearch-connector/src/handlers/search/__tests__/Configuration.test.ts
- packages/search-ui-elasticsearch-connector/src/handlers/search/index.ts
- packages/search-ui-elasticsearch-connector/src/index.ts
I have added support for optional `connectionOptions` as per #795 to be passed to the `ElasticsearchAPIConnector` constructor. For example:
```typescript
const connector = new ElasticsearchAPIConnector({
// ...
connectionOptions: {
// Optional connection options.
headers: {
"x-custom-header": "value" // Optional. Specify custom headers to send with the request
}
}
});
```
First time contributer so please let me know if I have failed to follow any of your coding standards/guidelines.
I didn't want to break the existing contracts but it probably would make sense eventually (as some sort of major version update) to place the `apiKey` inside the `connectionOptions` to match the SearchKitConfig interface.
1. Accept `connectionOptions` in `ElasticsearchAPIConnector`'s `config` parameter
2. …
> Support custom headers in Elasticsearch API Connector #795

- docs/api-core-configuration.mdx
- docs/api-react-components-search-box.mdx
- examples/vue/cleanseCards.js
- packages/react-search-ui-views/src/Autocomplete.tsx
- packages/react-search-ui-views/src/__tests__/Autocomplete.test.tsx
- packages/react-search-ui-views/src/__tests__/__snapshots__/Autocomplete.test.tsx.snap
- packages/search-ui-elasticsearch-connector/src/handlers/autocomplete/__tests__/index.test.ts
- packages/search-ui-elasticsearch-connector/src/handlers/autocomplete/index.ts
- packages/search-ui/src/types/index.ts
This change enables suggestions coming from a different index. An example of this would be searching across popular queries stored in another index
https://user-images.githubusercontent.com/49480/180554628-1c3f0f0d-f9e2-4acb-9225-5387d16aacd3.mov
> [Elasticsearch-connector] Suggestions from another Index source

- docs/api-react-components-results.mdx
It's not immediately apparent how to do this and someone asked about it so I thought I'd add it to our docs.
> Added a view customization example to Results

- packages/search-ui-app-search-connector/src/__tests__/AppSearchAPIConnector.test.ts
- packages/search-ui-app-search-connector/src/__tests__/requestAdapters.test.ts
- packages/search-ui-app-search-connector/src/requestAdapters.ts
fixes https://github.com/elastic/search-ui/issues/837. 
- We are currently creating a new "filter" per value, even if it was grouped together inside values. This hits a ceiling fast with only 32 filters can be applied. 
- we should be using one filter per field with an **array** of values. https://www.elastic.co/guide/en/app-search/current/filters.html#filters-arrays-all-none
- ranges will not be able to be grouped together. Requires a filter per range type
> Efficent generation of filters for App Search Connector 

- packages/react-search-ui/src/__tests__/helpers.test.ts
- packages/react-search-ui/src/containers/Facet.tsx
- packages/react-search-ui/src/containers/__tests__/Facet.test.tsx
- packages/react-search-ui/src/helpers.ts
When using a `<Facet isFilterable={true} />` on a field mapped to `NUMBER`, we get the following error:
`Uncaught TypeError: str.normalize is not a function`
1. If anything other than string passed as argument in `accentFold` function, it should return empty string.
2. Added a shield for facet values to be string.
Fixes #833
> fix the error while passing any data except string for normalization

- INTERNAL.md
The `start-docs` command was wrong. Additionally, the latest version of docs.elastic.co uses docsmobile 1.11 which uses a `content.js` file instead of a `sources.json` file.
> Fixed INTERNAL.md

- examples/sandbox/src/pages/app-search/index.js
- examples/sandbox/src/pages/elasticsearch/index.js
- packages/react-search-ui/src/containers/Facet.tsx
- packages/react-search-ui/src/containers/__tests__/Facet.test.tsx
Currently the ability to filter a Facet (`isFilterable` prop) does not work with range based facets for app-search, as the structure of the `value` property is different. Assuming this is intended, this change gives the ability to filter by that type of value.
If this is unintentional, we can change the connector to change the way the value structured in the response.
A bit of duck typing for the `value` property in `facetValues` to facilitate filtering better.
> Fix facet filters for ranges

- docs/guides-nextjs-integration.mdx
Updating the nextjs documentation to fix a couple of issues:
- if the search is present in a dynamic url, updating the url without the original params will fail. The fix is to extend the params with search ui params. Memo also needs to watch when router `isReady` so params can be provided.
In response to this discuss post: https://discuss.elastic.co/t/integrating-search-ui-with-nextjs-router-dynamic-routes/322248/5
> Nextjs Router Documentation

- CODEOWNERS
This PR adds a CODEOWNERS file, adds @elastic/search-ui-maintainers as the primary code owner.
> Adds CODEOWNERS

- packages/search-ui-engines-connector/src/handlers/__test__/transporter.test.ts
- packages/search-ui-engines-connector/src/handlers/autocomplete/__tests__/index.test.ts
- packages/search-ui-engines-connector/src/handlers/autocomplete/index.ts
- packages/search-ui-engines-connector/src/handlers/search/Configuration.ts
- packages/search-ui-engines-connector/src/handlers/search/__tests__/Configuration.node.test.ts
- packages/search-ui-engines-connector/src/handlers/search/__tests__/Configuration.test.ts
- packages/search-ui-engines-connector/src/handlers/search/__tests__/index.test.ts
- packages/search-ui-engines-connector/src/handlers/search/index.ts
- packages/search-ui-engines-connector/src/handlers/transporter.ts
- packages/search-ui-engines-connector/src/index.ts
- packages/search-ui-engines-connector/src/types.ts
Adding search preview page in kibana, a few issues came up:
- we need to be able to specify custom headers or use kibana's core http service
- we need to change the url to call the internal proxied API
- we cannot specify an api key. Kibana auth (when made through the core http service) will handle authentication concern.
I decided its best to just allow an instance of a transporter to handle the interaction between the API and Search-UI. This way we can use:
- kibana's core http
- specify configuration thats relevant to the transporter
So within kibana, the configuration will be:
```ts
class InternalEngineTransporter implements Transporter {
constructor(private http: HttpSetup, private engineName: string) {}
async performRequest(request: SearchReqest) {
const url = …
```
> Engines Connector: Allow Custom Transporter 

- .github/workflows/publish_docs_co.yml
We are refactoring our docs org secrets to segment our public from private docs. This PR updates the keys to the new ones.
After this is completed, @gtback will change the following secrets to private internal repos:
```
VERCEL_GITHUB_TOKEN
VERCEL_TOKEN
VERCEL_ORG_ID
```
> Update publish_docs_co.yml with new Org Secrets

- packages/search-ui-engines-connector/src/handlers/autocomplete/index.ts
- packages/search-ui-engines-connector/src/handlers/search/Configuration.ts
- packages/search-ui-engines-connector/src/handlers/search/Query.ts
- packages/search-ui-engines-connector/src/handlers/search/__tests__/Configuration.test.ts
Uses query_string to get over the difficulty of multiple search analyzers.
https://github.com/elastic/search-ui/assets/49480/51cb8a47-6a7b-4a2b-881f-b1cce1fd7411
> Search Applications: Use query_string for search_preview

- docs/api-connectors-elasticsearch.mdx
Fix doc example for the custom es query.
In order for the example to work with the config from this [tutorial](https://docs.elastic.co/search-ui/tutorials/elasticsearch#step-5-configure-search-ui), I have to:
- add the closing bracket for `map((fieldName)...` and
- adjust `const searchFields = queryConfig.searchQuery.search_fields` to `const searchFields = queryConfig.search_fields`
> Fix closing bracket and adjust path to access searchFields

- docs/api-react-components-result.mdx
Doc Example missing closing `/` for HTML tag.
Replace `>` with `/>` for `<Results resultView={CustomResultView}/>`
> [DOC] Closing results with />

- packages/search-ui-elasticsearch-connector/src/handlers/common.ts
- packages/search-ui-elasticsearch-connector/src/handlers/search/__tests__/Response.test.ts
Update the elasticsearch connector to fix mishandled falsy values
Any field which evaluates to false is returned as an empty object. This change fixes this to return the expected { raw: field value } construct.
Changes the mapping of fields to check for existence rather than truth.
#996
> fix: Issue 996 - falsy values in search results

- examples/sandbox/package.json
- examples/sandbox/src/Router.js
- examples/sandbox/src/index.js
The `initApm()` call is failing and causing the live demo to not load, removing it for now.
- Remove the `initApm()`
- #1008
> [Demo] remove apm init as it is broken

- package.json
This updates the project npm workspaces by removing the vue example app. This allowed the vue app to successfully `npm i`.
Now this does mean when running the vue example it will install deps from npm instead of being overridden to the local npm workspace packages, so testing local changes will require updating the dependency in the vue example manually.
- Removes the Vue demo from the project npm workspaces.
Closes #1019
> fix: remove vue demo from workspaces

- .circleci/config.yml
- docs/api-connectors-elasticsearch.mdx
- docs/api-react-components-result.mdx
- examples/sandbox/src/Router.js
- package.json
- packages/react-search-ui-views/package.json
- packages/react-search-ui-views/src/__tests__/__snapshots__/Paging.test.tsx.snap
- packages/react-search-ui-views/src/styles/themes/reference-ui/components/_paging.scss
- yarn.lock
This PR updates rc-pagination to v4 to remove the dependancy on core-js@2.
the markup and behaviour is the same between versions and no breaking changes that could impact downstream.
fixes https://github.com/elastic/search-ui/issues/1025
> [Dependency] Update rc pagination to v4

- examples/sandbox/package.json
- package.json
- packages/react-search-ui-views/package.json
- packages/react-search-ui/package.json
- yarn.lock
- updates the sandbox to use react 18
- update the peerDependencies to react 18
fixes https://github.com/elastic/search-ui/issues/1027
> Tweak peerDependencies for react 18.2.0

- packages/react-search-ui-views/package.json
- packages/react-search-ui/package.json
- packages/search-ui-analytics-plugin/package.json
- packages/search-ui-app-search-connector/package.json
- packages/search-ui-elasticsearch-connector/package.json
- packages/search-ui-engines-connector/package.json
- packages/search-ui-site-search-connector/package.json
- packages/search-ui-workplace-search-connector/package.json
- packages/search-ui/package.json
On Nuxt3 or Svelte projects, an 500 error is returned with this message :
> SyntaxError: Named export 'SearchDriver' not found. The requested module '@elastic/search-ui' is a CommonJS module, which may not support all module.exports as named exports.
Add correct exports on package.json files to use ESM module on SvelteKit or Nuxt
```
"exports": {
".": {
"import": "./lib/esm/index.js",
"require": "./lib/cjs/index.js"
}
}
}
```
Resolve #952 #938 #953
> Missing exports

- packages/react-search-ui-views/package.json
Fixes #1044
The styles in the `react-search-ui-views` package are public, so they should be declared as exports.
> Declare exports for react styles

- examples/vue/package.json
- packages/react-search-ui-views/package.json
- packages/react-search-ui-views/src/Autocomplete.tsx
- packages/react-search-ui-views/src/index.tsx
- packages/react-search-ui/package.json
- packages/search-ui-analytics-plugin/package.json
- packages/search-ui-app-search-connector/package.json
- packages/search-ui-elasticsearch-connector/package.json
- packages/search-ui-engines-connector/package.json
- packages/search-ui-site-search-connector/package.json
- packages/search-ui-workplace-search-connector/package.json
- packages/search-ui/package.json
- packages/search-ui/src/types/index.ts
- yarn.lock
Updates to `package.json` `exports` to include types and package.json
Additionally updated to TS v4.9 as during investigation we found that module support was not fully available in TS until v4.7
- Added `"types": "./lib/esm/index.d.ts"` to `"exports"` configs
- Updates TS to v4.9.3
- Misc. type and dep fixes
#1046
> Module support updates.

- .github/workflows/publish_docs_co.yml
We are migrating the content from docs.elastic.co to elastic.co/docs on Wednesday, June 12, 2024. As a part of this, will be having a content freeze while we switch out hosting providers. 
This PR will need to be merged during the freeze to facilitate that move.
> [DO NOT MERGE] Update publish_docs_co.yml to point to elastic.co/docs

- docs/overview.mdx
This is a non-visible change to indicate that the new build pipeline is successful and live on https://www.elastic.co/docs. Safe to merge this once out of draft
> Update overview.mdx to force a build

- packages/search-ui-elasticsearch-connector/src/handlers/search/Request.ts
- packages/search-ui-elasticsearch-connector/src/handlers/search/__tests__/Request.test.ts
The test uses the same array twice so the check for filters.includes() works.  In the real world the baseFilter and the filter are different.  So I have updated the test and changed the check to use basefilters.find().
applicable).
This PR addresses the problem with filters being applied more than once.  There is a test for this but it is broken as it uses the same value in two arrays to check for inclusion.  I have updated the test and …
> fix: issue 1062 - filters applied more than once

- packages/search-ui-elasticsearch-connector/src/handlers/search/Configuration.ts
- packages/search-ui-elasticsearch-connector/src/handlers/search/__tests__/Configuration.test.ts
Implement a check for date maths
applicable).
Date range filters could reasonably be expected to support date math.  (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-daterange-aggregation.html)
Currently the check used isValidDateString only checks for a valid absolute date.
Added a new method which is based on a regex to spot relative dates.  If it's not a relative date then will continue to …
> fix: Issue 1060 - date ranges - relative dates

- CODEOWNERS
After cleaning up Elastic teams, it's required to re-assign `search-ui` codeowners to the proper team.
This PR is dedicated to changing @elastic/search-ui-maintainers team to the @elastic/search-experiences-team in the `CODEOWNERS` file
> Set search-experiences-team as CODEOWNERS of the search-ui

- .github/workflows/docs-preview.yml
applicable).
Adds a workflow that will add a comment to each PR that touches a file relevant to the AsciiDoc docs build. The comment will look like:
Adds workflow file.
Related to https://github.com/elastic/docs/pull/3140 and #1093 
cc @joemcelroy
> Add doc-preview workflow

- docs/api-connectors-elasticsearch.asciidoc
- packages/search-ui-elasticsearch-connector/README.md
Relates to https://github.com/elastic/docs/pull/3160
This PR updates links that target the master branch of the documentation, for example links in https://www.elastic.co/guide/en/search-ui/current/api-connectors-elasticsearch.html
The are causing the following documentation build errors when we retire the master documentation:
```
...
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/search-ui/current/api-connectors-elasticsearch.html contains broken links to:
--
  | INFO:build_docs:   - en/kibana/master/api-keys.html
```
> [DOCS] Replace hard-coded links to master

- packages/react-search-ui-views/src/BooleanFacet.tsx
- packages/react-search-ui-views/src/__tests__/BooleanFacet.test.tsx
- packages/search-ui/src/__tests__/helpers.test.ts
- packages/search-ui/src/helpers.ts
The BooleanFacet component does not work correctly with the Elasticsearch connector, because it's use of 0/1 values and true/false.
https://github.com/elastic/search-ui/issues/851
> Add check for numeric facet value

- docs/api-connectors-elasticsearch.asciidoc
- docs/tutorials-connectors.asciidoc
- docs/tutorials-elasticsearch.asciidoc
- packages/search-ui-elasticsearch-connector/README.md
Remove "Technical preview" not as Elasticsearch connector goes in GA
> Remove technical preview note for elasticsearch connector

- docs/README.md
- docs/reference/api-core-actions.md
- docs/reference/api-core-configuration.md
- docs/reference/api-core-index.md
- docs/reference/api-react-components-facet.md
- docs/reference/toc.yml
- examples/sandbox/src/pages/elasticsearch-basic/index.jsx
- packages/react-search-ui-views/src/types/index.ts
- packages/react-search-ui/src/containers/Facet.tsx
- packages/react-search-ui/src/containers/__tests__/Facet.test.tsx
- packages/search-ui/src/__tests__/actions/addFilter.test.ts
- packages/search-ui/src/__tests__/actions/setFilter.test.ts
- packages/search-ui/src/__tests__/actions/setSearchTerm.test.ts
- packages/search-ui/src/actions/addFilter.ts
- packages/search-ui/src/actions/setFilter.ts
- packages/search-ui/src/actions/setSearchTerm.ts
- packages/search-ui/src/test/sharedTests.js
- packages/search-ui/src/types/index.ts
Added the ability to preserve selected filters when performing a new search. This provides more flexibility in managing filter states, especially in cases where certain filters need to persist between search queries.
- Added new persistent parameter to the Facet component: `<Facet field="states" label="States" persistent={true} />`
- Added persistent parameter to setFilter and addFilter actions
```
setFilter("states", "Alaska", "all", true);
addFilter("states", ["Alaska", "California"], "all", true);
```
- Updated documentation to reflect new functionality:
- Added description of persistent parameter in Facet component documentation
- Added description of persistent parameter in setFilter and addFilter actions documentation
- Updated usage examples in documentation
- #89
> Add persistent prop to filters

- docs/reference/api-react-components-results-per-page.md
- docs/reference/api-react-components-search-box.md
- docs/reference/index.md
- docs/reference/known-issues.md
- docs/reference/toc.yml
- docs/reference/tutorials.md
- Cleaning up broken links in the documentation and using new v3 syntax for admonitions.
- Restore the known issues page to the Search UI docs from [Docs-content](https://github.com/elastic/docs-content/blob/58e968578d2cf5a0d1f6d51bec25ba3e34eee18e/release-notes/known-issues/search-ui.md?plain=1)
https://github.com/elastic/search-docs-team/issues/275
> [DOCS] Cleanup broken links in documentation

- docs/reference/guides-analyzing-performance.md
- docs/reference/solutions-ecommerce-autocomplete.md
- docs/reference/solutions-ecommerce-carousel.md
- docs/reference/solutions-ecommerce-category-page.md
- docs/reference/solutions-ecommerce-product-detail-page.md
- docs/reference/solutions-ecommerce-search-page.md
- docs/reference/tutorials-app-search.md
- docs/reference/tutorials-elasticsearch-configure-search-ui.md
- docs/reference/tutorials-elasticsearch-install-connector.md
- docs/reference/tutorials-elasticsearch-setup-cloud.md
- docs/reference/tutorials-elasticsearch-setup-index.md
- docs/reference/tutorials-workplace-search.md
Fixes image paths to work with docs-assembler.
Notes for the reviewer:
* I was not able to get images in reference, extend, or release-notes to work using the `:::{image}` syntax because it seems to resolve differently than the Markdown `![]()` syntax. We should address this in docs-builder, but in order to get images working as soon as possible, I've used Markdown syntax and left us a `TO DO` in a code comment to add back the `screenshot` class where applicable. 
cc @leemthompo
> [docs] Fix image paths for docs-assembler

- lerna.json
- packages/react-search-ui-views/src/Paging.tsx
- yarn.lock
This PR fixes a runtime error caused by a missing .js file extension in an ESM import path.
Since strict ESM environments (e.g. Node.js with "type": "module" or .mjs files) require fully specified import paths, this change ensures compatibility by explicitly adding the .js extension where needed.
#1135
> Fix ESM import resolution error by adding missing file extension

- docs/reference/api-connectors-elasticsearch.md
- docs/reference/api-core-configuration.md
- examples/sandbox/src/pages/elasticsearch-basic/index.jsx
- packages/search-ui-elasticsearch-connector/src/queryBuilders/ResultsAutocompleteBuilder.ts
- packages/search-ui-elasticsearch-connector/src/queryBuilders/SearchQueryBuilder.ts
- packages/search-ui-elasticsearch-connector/src/queryBuilders/__tests__/ResultsAutocompleteBuilder.test.ts
- packages/search-ui-elasticsearch-connector/src/queryBuilders/__tests__/SearchQueryBuilder.test.ts
- packages/search-ui/src/types/index.ts
Support for a new `fuzziness` configuration option within the **searchQuery** or **autocomplete results** object in Search UI.
When set to `true`, and used with the Elasticsearch Connector, this option enables typo tolerance in search and autocomplete queries by internally applying `fuzziness: "AUTO"` to supported `multi_match` query types. This improves the user experience by allowing results to match despite minor spelling mistakes or typos.
This option is ignored by other connectors (e.g., App Search or Site Search).
**Why a boolean?**
We intentionally chose a boolean format (`fuzziness: true | false`) rather than exposing Elasticsearch-specific values like `"AUTO", 1, or AUTO:4,8` to maintain the abstraction layer of Search UI. Since other connectors do not support fuzziness at all, …
> [Elasticsearch Connector] Add fuzziness param

- docs/reference/api-connectors-elasticsearch.md
- packages/search-ui-elasticsearch-connector/src/queryBuilders/SearchQueryBuilder.ts
- packages/search-ui-elasticsearch-connector/src/queryBuilders/__tests__/SearchQueryBuilder.test.ts
- packages/search-ui-elasticsearch-connector/src/transformer/__tests__/filterTransformer.test.ts
- packages/search-ui-elasticsearch-connector/src/transformer/filterTransformer.ts
Fixes the issue where filterType="none" and filterType="any" on facet filters were not properly translated in the Elasticsearch Connector.
The update ensures that:
- filterType="none" is correctly translated to a must_not clause.
- filterType="any" is correctly translated to a should clause.
- filterType="all" continues to behave as must (default).
- Updated `aggs` and `post_filters` builder to include filterType on facet filters.
- Introduced proper handling for `none` and any filter types using `must_not` and `should`.
- Updated related tests.
#783
> Fix queries with filtering types

- packages/search-ui-elasticsearch-connector/src/queryBuilders/__tests__/SearchQueryBuilder.test.ts
- packages/search-ui-elasticsearch-connector/src/transformer/__tests__/filterTransformer.test.ts
- packages/search-ui-elasticsearch-connector/src/transformer/filterTransformer.ts
applicable).
previously when this package leveraged searchkit set gte: and lte: inside the request body for range queries.
https://github.com/searchkit/searchkit/blob/3805f655363e8a72a534807026aee67d01536d3a/packages/searchkit-sdk/src/facets/MultiQueryOptionsFacet.ts#L20
Apparently there is an issue with the type declarations in @elastic/elasticsearch where it says from: and to: are valid properties of a range query (they aren't) …
> update transformRangeFilterValue to use gte and lte over from and to

- packages/search-ui-elasticsearch-connector/src/handlers/__tests__/handleSearch.test.ts
- packages/search-ui-elasticsearch-connector/src/transformer/__tests__/responseTransformer.test.ts
- packages/search-ui-elasticsearch-connector/src/transformer/responseTransformer.ts
While trying to access `rawResponse.took` I noticed `rawResponse` is always `null` in `@elastic/search-ui-elasticsearch-connector`
- updates `rawResponse` to `response` instead of `null`
- updates necessary tests
> fix: rawResponse hard-coded to null

- packages/search-ui-elasticsearch-connector/src/handlers/handleAutocomplete.ts
- packages/search-ui-elasticsearch-connector/src/handlers/handleSearch.ts
- packages/search-ui-elasticsearch-connector/src/queryBuilders/BaseQueryBuilder.ts
- packages/search-ui-elasticsearch-connector/src/queryBuilders/ResultsAutocompleteBuilder.ts
- packages/search-ui-elasticsearch-connector/src/queryBuilders/SearchQueryBuilder.ts
- packages/search-ui-elasticsearch-connector/src/queryBuilders/SuggestionsAutocompleteBuilder.ts
- packages/search-ui-elasticsearch-connector/src/queryBuilders/__tests__/BaseQueryBuilder.test.ts
- packages/search-ui-elasticsearch-connector/src/queryBuilders/__tests__/ResultsAutocompleteBuilder.test.ts
- packages/search-ui-elasticsearch-connector/src/queryBuilders/__tests__/SearchQueryBuilder.test.ts
- packages/search-ui-elasticsearch-connector/src/queryBuilders/__tests__/SuggestionsAutocompleteBuilder.test.ts
- packages/search-ui-elasticsearch-connector/src/types.ts
Converts `getQueryFn` to an `async` function so that asynchronous work can be done when creating the query.
#1178
> Allow getQueryFn to return a promise.
